import type { Exam } from "./types";

export const EXAMS: Record<string, Exam> = {
  // ---- Piano · Lesson-level mastery quiz for L1.1 ----
  piano_l1_01_mastery: {
    id: "piano_l1_01_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_01_hand_shape",
    title: "Quick check: hand shape & Middle C",
    passThreshold: 0.67,
    questions: [
      {
        id: "q1", type: "mcq",
        prompt: "Where is Middle C on a piano?",
        options: [
          "The very first white key on the far left",
          "The white key just to the left of the 2-black-key group near the center",
          "Any key to the right of a black key",
          "The same key as the lowest note",
        ],
        correctIndex: 1,
        explanation: "Middle C sits immediately to the left of the two-black-key group closest to the piano's name.",
      },
      {
        id: "q2", type: "mcq",
        prompt: "What does good hand shape feel like?",
        options: [
          "Flat fingers, straight wrist",
          "Curved fingers as if gently holding a peach",
          "Fingers pressed tight together",
          "Bent wrist, tense knuckles",
        ],
        correctIndex: 1,
        explanation: "Relaxed, curved fingers protect your tendons and give you control.",
      },
      {
        id: "q3", type: "listening",
        prompt: "Which note is this?",
        audioRef: { notes: [{ pitch: "C4", startMs: 0, durationMs: 1200 }] },
        options: ["A4", "C4", "G4", "E4"],
        correctIndex: 1,
        explanation: "That's Middle C (C4) — the 'home' note we're learning from.",
      },
    ],
  },

  // ---- Piano · Lesson 1.2 — Rhythm ----
  piano_l1_02_mastery: {
    id: "piano_l1_02_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_02_rhythm",
    title: "Quick check: steady beat",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "How many beats does a quarter note get in 4/4?",
        options: ["Half a beat", "One beat", "Two beats", "Four beats"],
        correctIndex: 1,
        explanation: "In 4/4, the quarter note gets one beat — the same as one metronome click." },
      { id: "q2", type: "mcq",
        prompt: "Best practice when starting a tricky rhythm?",
        options: ["Play it as fast as you can", "Slow the metronome down", "Skip the hard part", "Just feel it"],
        correctIndex: 1,
        explanation: "Slow tempo builds accuracy. Speed comes from clean repetitions, never the other way around." },
      { id: "q3", type: "listening",
        prompt: "Which pattern is on the beat?",
        audioRef: { notes: [
          { pitch: "C4", startMs: 0, durationMs: 500 },
          { pitch: "C4", startMs: 500, durationMs: 500 },
          { pitch: "C4", startMs: 1000, durationMs: 1000 },
        ] },
        options: ["Rushing the second note", "Quarter – quarter – half, all on the beat", "All half notes", "Random spacing"],
        correctIndex: 1,
        explanation: "That's quarter-quarter-half, exactly on the 120 bpm click." },
    ],
  },

  // ---- Piano · Lesson 1.3 — First tune ----
  piano_l1_03_mastery: {
    id: "piano_l1_03_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_03_twinkle",
    title: "Quick check: Twinkle melody",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "In C-position right hand, which finger plays G?",
        options: ["1 (thumb)", "3", "4", "5 (pinky)"],
        correctIndex: 3,
        explanation: "Finger 5 — your pinky — plays G when your thumb is on C." },
      { id: "q2", type: "mcq",
        prompt: "The first notes of Twinkle are…",
        options: ["C C F F G G F", "C C G G A A G", "C D E F G A B", "E E G G A A G"],
        correctIndex: 1,
        explanation: "Twinkle opens C C G G A A G — 'Twinkle, twinkle, little star'." },
      { id: "q3", type: "listening",
        prompt: "Which tune is this?",
        audioRef: { notes: [
          { pitch: "C4", startMs: 0, durationMs: 500 },
          { pitch: "C4", startMs: 500, durationMs: 500 },
          { pitch: "G4", startMs: 1000, durationMs: 500 },
          { pitch: "G4", startMs: 1500, durationMs: 500 },
          { pitch: "A4", startMs: 2000, durationMs: 500 },
          { pitch: "A4", startMs: 2500, durationMs: 500 },
          { pitch: "G4", startMs: 3000, durationMs: 1000 },
        ] },
        options: ["Twinkle, Twinkle, Little Star", "Happy Birthday", "Mary Had a Little Lamb", "Jingle Bells"],
        correctIndex: 0,
        explanation: "That's the opening of Twinkle, Twinkle." },
    ],
  },

  // ---- Piano · Lesson 1.4 — Left hand ----
  piano_l1_04_mastery: {
    id: "piano_l1_04_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_04_left_hand",
    title: "Quick check: adding the left hand",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "In the left hand, finger 5 is your…",
        options: ["Thumb", "Index finger", "Pinky", "Ring finger"],
        correctIndex: 2,
        explanation: "Same system as the right hand — 1 is always thumb, 5 is always pinky. The position is mirrored." },
      { id: "q2", type: "mcq",
        prompt: "Middle C minus one octave is…",
        options: ["C3", "C5", "B3", "D4"],
        correctIndex: 0,
        explanation: "C3 is one octave (12 keys) below Middle C." },
      { id: "q3", type: "mcq",
        prompt: "At L1, how loud should your left hand be compared to the right?",
        options: ["Much louder", "Equal volume", "Quieter — it's the foundation", "Absolutely silent"],
        correctIndex: 2,
        explanation: "The bass is the foundation. Keep it supportive; let the melody sing over it." },
    ],
  },

  // ---- Piano · Lesson 1.5 — Two hands ----
  piano_l1_05_mastery: {
    id: "piano_l1_05_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_05_two_hands",
    title: "Quick check: both hands together",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Best practice tempo for your first two-hand attempt?",
        options: ["Performance tempo", "Half performance tempo", "As slow as you need — even 40 bpm", "Fast, to build muscle memory"],
        correctIndex: 2,
        explanation: "When coordination is new, speed is your enemy. 40–60 bpm is a fine starting point." },
      { id: "q2", type: "mcq",
        prompt: "The trick for two-hand coordination is…",
        options: [
          "Think about both hands at once",
          "Ignore the left hand entirely",
          "Focus on the rhythm both hands share",
          "Count out loud while playing",
        ],
        correctIndex: 2,
        explanation: "When both hands land on the same beat, you only have one timing to think about." },
      { id: "q3", type: "listening",
        prompt: "Which is the Twinkle melody?",
        audioRef: { notes: [
          { pitch: "C4", startMs: 0, durationMs: 400 },
          { pitch: "C4", startMs: 400, durationMs: 400 },
          { pitch: "G4", startMs: 800, durationMs: 400 },
          { pitch: "G4", startMs: 1200, durationMs: 400 },
          { pitch: "A4", startMs: 1600, durationMs: 400 },
          { pitch: "A4", startMs: 2000, durationMs: 400 },
          { pitch: "G4", startMs: 2400, durationMs: 800 },
        ] },
        options: ["Twinkle (bars 1-4)", "Mary Had a Little Lamb", "Frère Jacques", "A random scale"],
        correctIndex: 0,
        explanation: "Those are the opening bars of Twinkle." },
    ],
  },

  // ---- Piano · Lesson 1.6 — Full C-major scale ----
  piano_l1_06_mastery: {
    id: "piano_l1_06_mastery",
    scope: "lesson",
    instrumentId: "piano",
    lessonId: "piano_l1_06_thumb_under",
    title: "Quick check: thumb-under technique",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Why do pianists use thumb-under?",
        options: [
          "It sounds louder",
          "So one hand plays long scales smoothly without running out of fingers",
          "Tradition",
          "Modern pianos require it",
        ],
        correctIndex: 1,
        explanation: "Five fingers, eight scale notes — thumb-under is how one hand keeps flowing up and down." },
      { id: "q2", type: "mcq",
        prompt: "Ascending C major RH, which finger plays F?",
        options: ["2", "3", "1 (thumb, via thumb-under)", "5"],
        correctIndex: 2,
        explanation: "After finger 3 on E, your thumb tucks under to land on F." },
      { id: "q3", type: "listening",
        prompt: "Which scale is this?",
        audioRef: { notes: [
          { pitch: "C4", startMs: 0, durationMs: 300 },
          { pitch: "D4", startMs: 300, durationMs: 300 },
          { pitch: "E4", startMs: 600, durationMs: 300 },
          { pitch: "F4", startMs: 900, durationMs: 300 },
          { pitch: "G4", startMs: 1200, durationMs: 300 },
          { pitch: "A4", startMs: 1500, durationMs: 300 },
          { pitch: "B4", startMs: 1800, durationMs: 300 },
          { pitch: "C5", startMs: 2100, durationMs: 600 },
        ] },
        options: ["C major, one octave", "C minor", "Chromatic scale", "G major"],
        correctIndex: 0,
        explanation: "All white keys, C to C — that's C major." },
    ],
  },

  // ---- Piano · Lesson 2.1 — Treble staff ----
  piano_l2_01_mastery: {
    id: "piano_l2_01_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_01_staff",
    title: "Quick check: treble staff",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "The lines of the treble staff (bottom to top) are…",
        options: ["E G B D F", "F A C E", "G B D F A", "A C E G"],
        correctIndex: 0,
        explanation: "*Every Good Boy Does Fine* — E G B D F, bottom up." },
      { id: "q2", type: "mcq",
        prompt: "The spaces of the treble staff spell…",
        options: ["JAZZ", "FACE", "BEAT", "EGGS"],
        correctIndex: 1,
        explanation: "Bottom up: F A C E — the word FACE." },
      { id: "q3", type: "mcq",
        prompt: "Middle C lives…",
        options: ["On the bottom line of treble", "One ledger line below the treble staff", "On the top line of treble", "Inside the staff"],
        correctIndex: 1,
        explanation: "Middle C sits on its own ledger line just below the treble staff." },
    ],
  },

  // ---- Piano · Lesson 2.2 — Bass staff ----
  piano_l2_02_mastery: {
    id: "piano_l2_02_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_02_bass_staff",
    title: "Quick check: bass staff",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "The lines of the bass staff (bottom to top) are…",
        options: ["E G B D F", "G B D F A", "F A C E", "A C E G"],
        correctIndex: 1,
        explanation: "*Good Boys Do Fine Always* — G B D F A, bottom up." },
      { id: "q2", type: "mcq",
        prompt: "The spaces of the bass staff spell…",
        options: ["ACEG", "FACE", "BEAT", "JAZZ"],
        correctIndex: 0,
        explanation: "*All Cows Eat Grass* — A C E G, bottom up." },
      { id: "q3", type: "mcq",
        prompt: "Middle C vs. the bass staff — where does it sit?",
        options: ["On the top line", "One ledger line above the staff", "Inside the staff", "Only on treble"],
        correctIndex: 1,
        explanation: "Middle C sits on the ledger line immediately above the bass staff — both staves share it." },
    ],
  },

  // ---- Piano · Lesson 2.3 — Rests & ties ----
  piano_l2_03_mastery: {
    id: "piano_l2_03_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_03_rests_ties",
    title: "Quick check: rests & ties",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "A half rest equals how many beats of silence in 4/4?",
        options: ["1", "2", "3", "4"],
        correctIndex: 1,
        explanation: "Half rest = 2 beats. Same value as a half note." },
      { id: "q2", type: "mcq",
        prompt: "Two tied notes should be played as…",
        options: [
          "Two separate notes at the same pitch",
          "One sustained note with no re-strike",
          "Two notes half the length each",
          "The second note only",
        ],
        correctIndex: 1,
        explanation: "A tie joins the duration of both notes into one sustained sound — the second note is never re-struck." },
      { id: "q3", type: "listening",
        prompt: "Where is the rest?",
        audioRef: { notes: [
          { pitch: "C4", startMs: 0,    durationMs: 500 },
          { pitch: "E4", startMs: 500,  durationMs: 500 },
          { pitch: "G4", startMs: 1500, durationMs: 500 },
        ] },
        options: ["Beat 1", "Between beats 2 and 3", "Beat 4", "No rest"],
        correctIndex: 1,
        explanation: "The silence between the second note (beat 2) and the third note (beat 3) is a quarter rest." },
    ],
  },

  // ---- Piano · Lesson 2.4 — Accidentals ----
  piano_l2_04_mastery: {
    id: "piano_l2_04_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_04_accidentals",
    title: "Quick check: sharps, flats, naturals",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "A sharp (♯) tells you to…",
        options: ["Play one key higher", "Play one key lower", "Play twice", "Play softer"],
        correctIndex: 0,
        explanation: "Sharp = up one key (usually the adjacent black key)." },
      { id: "q2", type: "mcq",
        prompt: "F♯ and G♭ are…",
        options: ["The same note with different names", "Different notes", "Only valid in some keys", "An old notation style"],
        correctIndex: 0,
        explanation: "Same piano key — the name depends on the musical context (enharmonic equivalents)." },
      { id: "q3", type: "mcq",
        prompt: "An accidental in bar 3 applies to…",
        options: ["Only that specific note", "Every repeat of that letter-name in bar 3", "The rest of the piece", "All bars before it"],
        correctIndex: 1,
        explanation: "Accidentals reset at the barline. Within the bar, they apply to every same-letter note." },
    ],
  },

  // ---- Piano · Lesson 2.5 — Key signatures ----
  piano_l2_05_mastery: {
    id: "piano_l2_05_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_05_key_sigs",
    title: "Quick check: key signatures",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "No sharps or flats = which key?",
        options: ["G major", "C major", "F major", "D major"],
        correctIndex: 1,
        explanation: "All white keys — C major (or A minor, its relative)." },
      { id: "q2", type: "mcq",
        prompt: "One sharp (F♯) = which major key?",
        options: ["C", "G", "D", "F"],
        correctIndex: 1,
        explanation: "G major contains one sharp — F♯. It's the next step up the circle of fifths from C." },
      { id: "q3", type: "mcq",
        prompt: "One flat (B♭) = which major key?",
        options: ["F", "G", "B♭", "C"],
        correctIndex: 0,
        explanation: "F major has one flat (B♭). One step in the flat direction from C." },
    ],
  },

  // ---- Piano · Lesson 2.6 — Dynamics ----
  piano_l2_06_mastery: {
    id: "piano_l2_06_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l2_06_dynamics",
    title: "Quick check: dynamics",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Which marking is the softest?",
        options: ["f", "mf", "p", "pp"],
        correctIndex: 3,
        explanation: "pp (pianissimo) = very soft. Quieter than p (piano)." },
      { id: "q2", type: "mcq",
        prompt: "A crescendo tells you to…",
        options: ["Get gradually louder", "Get gradually softer", "Play faster", "Stop"],
        correctIndex: 0,
        explanation: "Crescendo (`<` or *cresc.*) = gradually louder over the phrase." },
      { id: "q3", type: "mcq",
        prompt: "The right way to play louder is…",
        options: ["Tense your shoulder", "Let arm weight fall into the key", "Squeeze the key harder", "Stab the key"],
        correctIndex: 1,
        explanation: "Loud comes from dropped weight, not muscle tension. Tension kills tone and will injure you." },
    ],
  },

  // ---- Piano · L3 lesson mastery quizzes ----
  piano_l3_01_mastery: {
    id: "piano_l3_01_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_01_ode_to_joy",
    title: "Quick check: Ode to Joy",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Ode to Joy is by…",
        options: ["Mozart", "Beethoven", "Bach", "Chopin"],
        correctIndex: 1,
        explanation: "Beethoven's 9th Symphony, final movement." },
      { id: "q2", type: "mcq",
        prompt: "The melody uses how many different notes?",
        options: ["3", "4 or 5", "7 or 8", "A full octave"],
        correctIndex: 1,
        explanation: "Mostly E, D, F, G — four core notes plus a C." },
      { id: "q3", type: "listening",
        prompt: "Which tune is this?",
        audioRef: { notes: [
          { pitch: "E4", startMs: 0,    durationMs: 500 },
          { pitch: "E4", startMs: 500,  durationMs: 500 },
          { pitch: "F4", startMs: 1000, durationMs: 500 },
          { pitch: "G4", startMs: 1500, durationMs: 500 },
          { pitch: "G4", startMs: 2000, durationMs: 500 },
          { pitch: "F4", startMs: 2500, durationMs: 500 },
          { pitch: "E4", startMs: 3000, durationMs: 500 },
          { pitch: "D4", startMs: 3500, durationMs: 500 },
        ] },
        options: ["Twinkle", "Ode to Joy", "Für Elise", "Happy Birthday"],
        correctIndex: 1,
        explanation: "That's the opening 8 notes of Ode to Joy." },
    ],
  },
  piano_l3_02_mastery: {
    id: "piano_l3_02_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_02_amazing_grace",
    title: "Quick check: Amazing Grace",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Amazing Grace is in what time signature?",
        options: ["4/4", "3/4", "6/8", "2/4"],
        correctIndex: 1,
        explanation: "3/4 — a waltz feel: ONE two three, ONE two three." },
      { id: "q2", type: "mcq",
        prompt: "The song starts on beat…",
        options: ["1", "2", "3 (pickup)", "4"],
        correctIndex: 2,
        explanation: "'A-' is a pickup note on beat 3, leading into 'MAZ-ing' on beat 1 of bar 1." },
      { id: "q3", type: "mcq",
        prompt: "A dotted half note in 3/4 lasts…",
        options: ["1 beat", "2 beats", "3 beats (a full bar)", "4 beats"],
        correctIndex: 2,
        explanation: "Dotted half = half + extra half of its value = 3 beats, the whole bar in 3/4." },
    ],
  },
  piano_l3_03_mastery: {
    id: "piano_l3_03_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_03_keertanam",
    title: "Quick check: Mohanam on piano",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Raga Mohanam uses how many different notes?",
        options: ["5", "6", "7", "8"],
        correctIndex: 0,
        explanation: "Mohanam is pentatonic — 5 notes: Sa Ri Ga Pa Dha (C D E G A)." },
      { id: "q2", type: "mcq",
        prompt: "Which piano keys represent Mohanam in C?",
        options: ["C D E F G", "C D E G A", "C E G B D", "All black keys"],
        correctIndex: 1,
        explanation: "Sa=C, Ri=D, Ga=E, Pa=G, Dha=A. Notice there's no F (Ma) or B (Ni)." },
      { id: "q3", type: "mcq",
        prompt: "A gamaka is…",
        options: ["A drum beat", "An ornament — a slide or bend into a note", "A tempo", "A rest"],
        correctIndex: 1,
        explanation: "Gamakas are the ornaments that give Indian classical its character — slides, bends, oscillations on a note." },
    ],
  },
  piano_l3_04_mastery: {
    id: "piano_l3_04_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_04_autumn_leaves",
    title: "Quick check: Autumn Leaves",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "Autumn Leaves is in what key?",
        options: ["C major", "E minor", "G major", "A minor"],
        correctIndex: 1,
        explanation: "E minor (relative of G major). The melancholy is baked into the key." },
      { id: "q2", type: "mcq",
        prompt: "The melodic shape of each A-section phrase…",
        options: ["Climbs higher", "Descends lower each time", "Stays on one note", "Jumps around randomly"],
        correctIndex: 1,
        explanation: "The phrases step lower and lower — that descent IS the song's emotional arc." },
      { id: "q3", type: "mcq",
        prompt: "Minor key music is…",
        options: ["Always sad", "Weighted, contemplative — not necessarily sad", "Only for classical", "Technically incorrect"],
        correctIndex: 1,
        explanation: "Minor = weighted. It can be sad, but it can also be mysterious, regal, or just reflective." },
    ],
  },
  piano_l3_05_mastery: {
    id: "piano_l3_05_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_05_hanon",
    title: "Quick check: Hanon #1",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "What is the goal of Hanon exercises?",
        options: ["Musical expression", "Finger evenness + independence", "Memorization", "Improvisation"],
        correctIndex: 1,
        explanation: "Hanon is gym for fingers. Evenness and independence — not musicality." },
      { id: "q2", type: "mcq",
        prompt: "If one finger plays quieter than others, you should…",
        options: ["Ignore it", "Press harder with that finger", "Slow the metronome until evenness returns", "Skip the exercise"],
        correctIndex: 2,
        explanation: "Slow down until EVERY finger plays at the same volume. Then gradually speed up." },
      { id: "q3", type: "mcq",
        prompt: "How long should you do Hanon in a practice session?",
        options: ["2 hours", "30 minutes", "5-10 minutes as a warm-up", "Only once a week"],
        correctIndex: 2,
        explanation: "A focused 5-10 min warm-up is enough. More than 15 min risks injury without benefit." },
    ],
  },
  piano_l3_06_mastery: {
    id: "piano_l3_06_mastery",
    scope: "lesson", instrumentId: "piano", lessonId: "piano_l3_06_accompaniment",
    title: "Quick check: chord accompaniment",
    passThreshold: 0.67,
    questions: [
      { id: "q1", type: "mcq",
        prompt: "In C major, a C chord contains…",
        options: ["C D E", "C E G", "C F G", "C G C"],
        correctIndex: 1,
        explanation: "C major triad = root (C) + third (E) + fifth (G)." },
      { id: "q2", type: "mcq",
        prompt: "The V chord in C major is…",
        options: ["F", "G", "A minor", "D"],
        correctIndex: 1,
        explanation: "V = 5th scale degree. In C major, that's G — so a G major chord (G B D)." },
      { id: "q3", type: "mcq",
        prompt: "Why does V want to resolve to I?",
        options: [
          "Tradition",
          "The 7th of V (F in a G7) is a half-step below the 8th of I (C) — tension → release",
          "It's a rule someone made up",
          "It doesn't, that's a myth",
        ],
        correctIndex: 1,
        explanation: "The leading tone (major 7th of the key) pulls strongly to the tonic. That's the pull of V→I." },
    ],
  },

  // ---- Piano · Level 1 → Level 2 advancement exam ----
  piano_l1_level_exam: {
    id: "piano_l1_level_exam",
    scope: "level",
    instrumentId: "piano",
    level: 1,
    title: "Level 1 exam — Foundations",
    passThreshold: 0.8,
    questions: [
      {
        id: "q1", type: "mcq",
        prompt: "How many beats does a half note get in 4/4?",
        options: ["1", "2", "3", "4"],
        correctIndex: 1,
        explanation: "A half note = 2 quarter notes = 2 beats.",
      },
      {
        id: "q2", type: "mcq",
        prompt: "In C-position right hand, which finger plays F?",
        options: ["1 (thumb)", "2", "3", "4"],
        correctIndex: 3,
        explanation: "Finger 4 (ring) plays F when thumb is on C.",
      },
      {
        id: "q3", type: "listening",
        prompt: "What scale pattern is this?",
        audioRef: {
          notes: [
            { pitch: "C4", startMs: 0, durationMs: 400 },
            { pitch: "D4", startMs: 400, durationMs: 400 },
            { pitch: "E4", startMs: 800, durationMs: 400 },
            { pitch: "F4", startMs: 1200, durationMs: 400 },
            { pitch: "G4", startMs: 1600, durationMs: 600 },
          ],
        },
        options: ["C to G ascending", "G to C descending", "Random notes", "The same note five times"],
        correctIndex: 0,
        explanation: "You heard C–D–E–F–G — the first five notes of C major ascending.",
      },
      {
        id: "q4", type: "mcq",
        prompt: "What's a steady tempo?",
        options: [
          "Playing as fast as possible",
          "Each beat lands the same time apart",
          "Slowing down in hard parts",
          "It doesn't matter for beginners",
        ],
        correctIndex: 1,
        explanation: "Steady tempo means equal time between beats — the backbone of all music.",
      },
      {
        id: "q5", type: "listening",
        prompt: "Which of these is in rhythm with a steady click?",
        audioRef: {
          notes: [
            { pitch: "C4", startMs: 0, durationMs: 500 },
            { pitch: "C4", startMs: 500, durationMs: 500 },
            { pitch: "C4", startMs: 1000, durationMs: 500 },
            { pitch: "C4", startMs: 1500, durationMs: 500 },
          ],
        },
        options: ["Rushing — the notes speed up", "Steady quarter notes", "Random timing", "Too slow to count"],
        correctIndex: 1,
        explanation: "Four equal quarter notes at steady 120 bpm.",
      },
    ],
  },

  // ---- Piano · Standard Certificate (L3) tier exam ----
  piano_standard_certificate: {
    id: "piano_standard_certificate",
    scope: "grade",
    instrumentId: "piano",
    tier: "standard",
    title: "Standard Certificate — Piano",
    passThreshold: 0.85,
    questions: [
      {
        id: "q1", type: "mcq",
        prompt: "Which sequence is a C major scale?",
        options: [
          "C D E F# G A B C",
          "C D E F G A B C",
          "C Db Eb F G Ab Bb C",
          "C D E F G A Bb C",
        ],
        correctIndex: 1,
        explanation: "C major has no sharps or flats — just the white keys from C to C.",
      },
      {
        id: "q2", type: "practical",
        prompt: "Play the C major 5-finger scale ascending and descending, steady at 60 bpm.",
        exerciseId: "piano_l1_01_scale5",
        minComposite: 0.75,
        explanation: "This is the gating practical — your live take is graded by the audio engine.",
      },
      {
        id: "q3", type: "listening",
        prompt: "Which pattern did you hear?",
        audioRef: {
          notes: [
            { pitch: "C4", startMs: 0, durationMs: 400 },
            { pitch: "E4", startMs: 400, durationMs: 400 },
            { pitch: "G4", startMs: 800, durationMs: 400 },
            { pitch: "C5", startMs: 1200, durationMs: 600 },
          ],
        },
        options: ["C major triad arpeggio", "C minor triad", "Descending scale", "C E G B"],
        correctIndex: 0,
        explanation: "C → E → G → C is a C major arpeggio.",
      },
    ],
  },
};

export const getExam = (id: string) => EXAMS[id];

export const examForLesson = (lessonId: string): Exam | undefined =>
  Object.values(EXAMS).find((e) => e.scope === "lesson" && e.lessonId === lessonId);

export const examForLevel = (instrumentId: string, level: number): Exam | undefined =>
  Object.values(EXAMS).find((e) => e.scope === "level" && e.instrumentId === instrumentId && e.level === level);

export const examForGrade = (instrumentId: string, tier: "standard" | "pro" | "genius"): Exam | undefined =>
  Object.values(EXAMS).find((e) => e.scope === "grade" && e.instrumentId === instrumentId && e.tier === tier);
