import type { Instrument } from "./types";

export const INSTRUMENTS: Record<string, Instrument> = {
  piano: {
    id: "piano",
    name: "Piano",
    family: "keyboard",
    origin: "western",
    accent: "keyboard",
    glyph: "🎹",
    blurb: "The most visual instrument on earth. One key, one note — perfect for learning.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "sustain_pedal", name: "Sustain pedal", label: "Sustain",
        description: "Lifts all dampers off the strings so every note rings on after you release the key." },
      { id: "soft_pedal", name: "Una corda", label: "Soft",
        description: "Shifts the hammers sideways so they strike two strings instead of three — softer, gentler tone." },
      { id: "middle_pedal", name: "Sostenuto", label: "Sostenuto",
        description: "Holds only the notes you were pressing when you stepped on it. A magician's pedal." },
    ],
    sampleAudio: [
      { id: "c4", label: "Middle C", noteName: "C4" },
      { id: "chord_cmaj", label: "C major chord" },
      { id: "scale_cmaj", label: "C major scale" },
    ],
    pedagogyTrackId: "piano_standard",
    difficultyFloor: 1,
    micSetupHints: [
      "Phone or laptop mic ~30cm above middle C works great.",
      "Keep the room quiet — we're measuring pitch to within 40 cents.",
    ],
  },
  guitar: {
    id: "guitar",
    name: "Guitar",
    family: "fretted",
    origin: "western",
    accent: "fretted",
    glyph: "🎸",
    blurb: "Six strings, infinite songs. Frets make pitch foolproof; rhythm is where you'll earn it.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "tuning_pegs", name: "Tuning pegs", label: "Tune", description: "Rotate to tighten or loosen each string. E A D G B E." },
      { id: "capo", name: "Capo", label: "Capo", description: "Clamp across a fret to raise the key without changing your chord shapes." },
    ],
    sampleAudio: [
      { id: "e_open", label: "Open E (low)" },
      { id: "chord_g", label: "G major" },
    ],
    pedagogyTrackId: "guitar_standard",
    difficultyFloor: 1,
    micSetupHints: ["Acoustic: mic at the 12th fret. Electric: line-in or mic'd amp."],
  },
  sitar: {
    id: "sitar",
    name: "Sitar",
    family: "fretted",
    origin: "indian_classical",
    accent: "indian",
    glyph: "🪕",
    blurb: "The voice of Hindustani classical. Curved frets, sympathetic strings, infinite glide.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "meend", name: "Meend", label: "String bend glide",
        description: "Pull a string laterally across the curved fret to bend pitch up to 5 semitones." },
      { id: "taraf", name: "Taraf", label: "Sympathetic strings",
        description: "Untouched strings tuned to the raga — they ring out on their own." },
      { id: "mizrab", name: "Mizrab", label: "Plectrum",
        description: "Wire plectrum worn on the index finger. Down-stroke: Da. Up-stroke: Ra." },
    ],
    sampleAudio: [
      { id: "sa", label: "Sa (tonic)" },
      { id: "meend_demo", label: "Meend demo" },
      { id: "yaman_phrase", label: "Raga Yaman phrase" },
    ],
    pedagogyTrackId: "sitar_standard",
    difficultyFloor: 2,
    micSetupHints: ["Mic at the tumba (gourd) ~20cm away — capture the resonance."],
  },
  tabla: {
    id: "tabla",
    name: "Tabla",
    family: "perc_pitched",
    origin: "indian_classical",
    accent: "indian",
    glyph: "🥁",
    blurb: "Two drums, one language: bols. Dha, Dhin, Na, Tin — the vocabulary of every taal.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "syahi", name: "Syahi", label: "Tuning paste",
        description: "The black circle is iron oxide paste — it gives tabla its pitched ring." },
      { id: "chati", name: "Chati", label: "Rim strike",
        description: "Edge strikes (Ti, Ta, Na) produce the bright, unpitched sounds." },
    ],
    sampleAudio: [
      { id: "dha", label: "Dha" }, { id: "dhin", label: "Dhin" },
      { id: "na", label: "Na" }, { id: "tin", label: "Tin" },
      { id: "teentaal", label: "Teentaal theka" },
    ],
    pedagogyTrackId: "tabla_standard",
    difficultyFloor: 1,
    micSetupHints: ["One mic between the two drums, or two spot mics for Dayan (right) + Bayan (left)."],
  },
  violin: {
    id: "violin",
    name: "Violin",
    family: "bowed",
    origin: "western",
    accent: "bowed",
    glyph: "🎻",
    blurb: "No frets means every millimeter matters. The instrument that teaches you to listen.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "bow_pressure", name: "Bow pressure", label: "Pressure", description: "Weight of the bow on the string. More = louder, but watch for scratchy tone." },
      { id: "contact_point", name: "Contact point", label: "Sul tasto ↔ ponticello", description: "Where on the string you bow. Over the fingerboard = airy. Near the bridge = glassy." },
    ],
    sampleAudio: [
      { id: "open_a", label: "Open A (440Hz)" },
      { id: "vibrato", label: "Vibrato demo" },
    ],
    pedagogyTrackId: "violin_standard",
    difficultyFloor: 2,
    micSetupHints: ["Mic above and slightly in front of the f-holes, 30–50cm away."],
  },
  flute: {
    id: "flute",
    name: "Flute",
    family: "woodwind",
    origin: "western",
    accent: "voice",
    glyph: "🪈",
    blurb: "Breath becomes pitch. Simple keys, deceptively hard embouchure.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "embouchure", name: "Embouchure", label: "Lip shape", description: "The aperture of your lips shapes tone and pitch. Tight = sharp + thin; loose = flat + airy." },
    ],
    sampleAudio: [{ id: "a4", label: "A4" }, { id: "scale_c", label: "C major scale" }],
    pedagogyTrackId: "flute_standard",
    difficultyFloor: 1,
    micSetupHints: ["Mic above the headjoint, not pointed at the embouchure hole — too breathy."],
  },
  vocals: {
    id: "vocals",
    name: "Vocals",
    family: "voice",
    origin: "global",
    accent: "voice",
    glyph: "🎤",
    blurb: "Your built-in instrument. Pitch detection works cleanest here — the fastest to Level 1.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "register", name: "Register", label: "Chest / head / mixed", description: "Where the resonance sits. Chest for low, head for high, mixed for pop belts." },
    ],
    sampleAudio: [{ id: "do", label: "Do (scale degree 1)" }],
    pedagogyTrackId: "vocals_standard",
    difficultyFloor: 1,
    micSetupHints: ["10–15cm from your mouth. Cardioid pattern if you have one."],
  },
  drums: {
    id: "drums",
    name: "Drum kit",
    family: "perc_unpitched",
    origin: "western",
    accent: "perc",
    glyph: "🥁",
    blurb: "Four limbs, one groove. The instrument where rhythm is the *only* pitch.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "hi_hat", name: "Hi-hat", label: "Open / closed", description: "Foot down = tight chick. Foot partly up = sizzle. Foot up = washy splash." },
    ],
    sampleAudio: [{ id: "backbeat", label: "Backbeat 2+4" }],
    pedagogyTrackId: "drums_standard",
    difficultyFloor: 1,
    micSetupHints: ["Room mic at ear height, or overheads + kick mic for detail."],
  },
};

export const listInstruments = () => Object.values(INSTRUMENTS);
export const getInstrument = (id: string) => INSTRUMENTS[id];
