import type { Instrument } from "./types";

export const INSTRUMENTS: Record<string, Instrument> = {
  piano: {
    id: "piano",
    name: "Piano",
    family: "keyboard",
    origin: "western",
    accent: "keyboard",
    glyph: "🎹",
    blurb: "The most visual instrument on earth. One key, one note — perfect for learning.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "sustain_pedal", name: "Sustain pedal", label: "Sustain",
        description: "Lifts all dampers off the strings so every note rings on after you release the key." },
      { id: "soft_pedal", name: "Una corda", label: "Soft",
        description: "Shifts the hammers sideways so they strike two strings instead of three — softer, gentler tone." },
      { id: "middle_pedal", name: "Sostenuto", label: "Sostenuto",
        description: "Holds only the notes you were pressing when you stepped on it. A magician's pedal." },
    ],
    sampleAudio: [
      { id: "c4", label: "Middle C", noteName: "C4" },
      { id: "chord_cmaj", label: "C major chord" },
      { id: "scale_cmaj", label: "C major scale" },
    ],
    pedagogyTrackId: "piano_standard",
    difficultyFloor: 1,
    micSetupHints: [
      "Phone or laptop mic ~30cm above middle C works great.",
      "Keep the room quiet — we're measuring pitch to within 40 cents.",
    ],
  },
  guitar: {
    id: "guitar",
    name: "Guitar",
    family: "fretted",
    origin: "western",
    accent: "fretted",
    glyph: "🎸",
    blurb: "Six strings, infinite songs. Frets make pitch foolproof; rhythm is where you'll earn it.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "tuning_pegs", name: "Tuning pegs", label: "Tune", description: "Rotate to tighten or loosen each string. E A D G B E." },
      { id: "capo", name: "Capo", label: "Capo", description: "Clamp across a fret to raise the key without changing your chord shapes." },
    ],
    sampleAudio: [
      { id: "e_open", label: "Open E (low)" },
      { id: "chord_g", label: "G major" },
    ],
    pedagogyTrackId: "guitar_standard",
    difficultyFloor: 1,
    micSetupHints: ["Acoustic: mic at the 12th fret. Electric: line-in or mic'd amp."],
  },
  sitar: {
    id: "sitar",
    name: "Sitar",
    family: "fretted",
    origin: "indian_classical",
    accent: "indian",
    glyph: "🪕",
    blurb: "The voice of Hindustani classical. Curved frets, sympathetic strings, infinite glide.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "meend", name: "Meend", label: "String bend glide",
        description: "Pull a string laterally across the curved fret to bend pitch up to 5 semitones." },
      { id: "taraf", name: "Taraf", label: "Sympathetic strings",
        description: "Untouched strings tuned to the raga — they ring out on their own." },
      { id: "mizrab", name: "Mizrab", label: "Plectrum",
        description: "Wire plectrum worn on the index finger. Down-stroke: Da. Up-stroke: Ra." },
    ],
    sampleAudio: [
      { id: "sa", label: "Sa (tonic)" },
      { id: "meend_demo", label: "Meend demo" },
      { id: "yaman_phrase", label: "Raga Yaman phrase" },
    ],
    pedagogyTrackId: "sitar_standard",
    difficultyFloor: 2,
    micSetupHints: ["Mic at the tumba (gourd) ~20cm away — capture the resonance."],
  },
  tabla: {
    id: "tabla",
    name: "Tabla",
    family: "perc_pitched",
    origin: "indian_classical",
    accent: "indian",
    glyph: "🥁",
    blurb: "Two drums, one language: bols. Dha, Dhin, Na, Tin — the vocabulary of every taal.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "syahi", name: "Syahi", label: "Tuning paste",
        description: "The black circle is iron oxide paste — it gives tabla its pitched ring." },
      { id: "chati", name: "Chati", label: "Rim strike",
        description: "Edge strikes (Ti, Ta, Na) produce the bright, unpitched sounds." },
    ],
    sampleAudio: [
      { id: "dha", label: "Dha" }, { id: "dhin", label: "Dhin" },
      { id: "na", label: "Na" }, { id: "tin", label: "Tin" },
      { id: "teentaal", label: "Teentaal theka" },
    ],
    pedagogyTrackId: "tabla_standard",
    difficultyFloor: 1,
    micSetupHints: ["One mic between the two drums, or two spot mics for Dayan (right) + Bayan (left)."],
  },
  violin: {
    id: "violin",
    name: "Violin",
    family: "bowed",
    origin: "western",
    accent: "bowed",
    glyph: "🎻",
    blurb: "No frets means every millimeter matters. The instrument that teaches you to listen.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "bow_pressure", name: "Bow pressure", label: "Pressure", description: "Weight of the bow on the string. More = louder, but watch for scratchy tone." },
      { id: "contact_point", name: "Contact point", label: "Sul tasto ↔ ponticello", description: "Where on the string you bow. Over the fingerboard = airy. Near the bridge = glassy." },
    ],
    sampleAudio: [
      { id: "open_a", label: "Open A (440Hz)" },
      { id: "vibrato", label: "Vibrato demo" },
    ],
    pedagogyTrackId: "violin_standard",
    difficultyFloor: 2,
    micSetupHints: ["Mic above and slightly in front of the f-holes, 30–50cm away."],
  },
  flute: {
    id: "flute",
    name: "Flute",
    family: "woodwind",
    origin: "western",
    accent: "voice",
    glyph: "🪈",
    blurb: "Breath becomes pitch. Simple keys, deceptively hard embouchure.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "embouchure", name: "Embouchure", label: "Lip shape", description: "The aperture of your lips shapes tone and pitch. Tight = sharp + thin; loose = flat + airy." },
    ],
    sampleAudio: [{ id: "a4", label: "A4" }, { id: "scale_c", label: "C major scale" }],
    pedagogyTrackId: "flute_standard",
    difficultyFloor: 1,
    micSetupHints: ["Mic above the headjoint, not pointed at the embouchure hole — too breathy."],
  },
  vocals: {
    id: "vocals",
    name: "Vocals",
    family: "voice",
    origin: "global",
    accent: "voice",
    glyph: "🎤",
    blurb: "Your built-in instrument. Pitch detection works cleanest here — the fastest to Level 1.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "register", name: "Register", label: "Chest / head / mixed", description: "Where the resonance sits. Chest for low, head for high, mixed for pop belts." },
    ],
    sampleAudio: [{ id: "do", label: "Do (scale degree 1)" }],
    pedagogyTrackId: "vocals_standard",
    difficultyFloor: 1,
    micSetupHints: ["10–15cm from your mouth. Cardioid pattern if you have one."],
  },
  drums: {
    id: "drums",
    name: "Drum kit",
    family: "perc_unpitched",
    origin: "western",
    accent: "perc",
    glyph: "🥁",
    blurb: "Four limbs, one groove. The instrument where rhythm is the *only* pitch.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "hi_hat", name: "Hi-hat", label: "Open / closed", description: "Foot down = tight chick. Foot partly up = sizzle. Foot up = washy splash." },
    ],
    sampleAudio: [{ id: "backbeat", label: "Backbeat 2+4" }],
    pedagogyTrackId: "drums_standard",
    difficultyFloor: 1,
    micSetupHints: ["Room mic at ear height, or overheads + kick mic for detail."],
  },

  // ========================================================================
  // Phase 7+ · Expansion roster — 14 new instruments. Each ships with L1
  // kickoff content; full L2-L9 arcs roll out in subsequent content sprints.
  // ========================================================================
  bass: {
    id: "bass", name: "Bass guitar", family: "fretted", origin: "western", accent: "fretted", glyph: "🎸",
    blurb: "The groove foundation. Four strings, four strong opinions on where the beat lives.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "fingers_vs_pick", name: "Fingers vs pick", label: "Attack", description: "Fingerstyle = warm, rounded. Pick = percussive, consistent. Slap = funk." },
      { id: "tone_knob", name: "Tone", label: "Tone", description: "Roll off for Motown warmth, roll on for rock clarity." },
    ],
    sampleAudio: [{ id: "e_open", label: "Open E (low)" }, { id: "walking", label: "Walking bass line" }],
    pedagogyTrackId: "bass_standard", difficultyFloor: 1,
    micSetupHints: ["Best: direct-in (DI box). Mic option: amp cab ~15cm from grille."],
  },
  ukulele: {
    id: "ukulele", name: "Ukulele", family: "fretted", origin: "global", accent: "fretted", glyph: "🎶",
    blurb: "Four nylon strings, endless joy. The easiest fretted instrument to get started on.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "strum", name: "Strum pattern", label: "Strum", description: "Down-down-up-up-down-up = Hawaiian default. Thumb = soft, fingers = bright." },
    ],
    sampleAudio: [{ id: "c_chord", label: "C major chord" }, { id: "island_strum", label: "Island strum" }],
    pedagogyTrackId: "ukulele_standard", difficultyFloor: 1,
    micSetupHints: ["Phone mic 20cm away works great. Ukulele's quiet — kill room noise."],
  },
  mandolin: {
    id: "mandolin", name: "Mandolin", family: "fretted", origin: "western", accent: "fretted", glyph: "🪕",
    blurb: "Eight strings in four courses. Bluegrass, Italian folk, classical — a polyglot.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "tremolo", name: "Tremolo", label: "Tremolo", description: "Rapid alternate-picking to sustain a note the mandolin can't naturally hold." },
    ],
    sampleAudio: [{ id: "g_chord", label: "G chord" }, { id: "tremolo_demo", label: "Tremolo on A" }],
    pedagogyTrackId: "mandolin_standard", difficultyFloor: 2,
    micSetupHints: ["Mic ~30cm above the f-holes."],
  },
  bansuri: {
    id: "bansuri", name: "Bansuri", family: "woodwind", origin: "indian_classical", accent: "indian", glyph: "🎴",
    blurb: "The bamboo flute of Krishna. Breath, finger-hole coverage, and meend through embouchure.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "embouchure", name: "Embouchure", label: "Lip shape", description: "Angle of lips against the blow-hole determines octave + tone." },
      { id: "finger_meend", name: "Finger meend", label: "Half-hole glide", description: "Gradually uncovering a hole slides pitch — bansuri's version of sitar meend." },
    ],
    sampleAudio: [{ id: "sa", label: "Sa" }, { id: "yaman", label: "Raga Yaman phrase" }],
    pedagogyTrackId: "bansuri_standard", difficultyFloor: 3,
    micSetupHints: ["Mic below embouchure hole; avoid breath noise by angling 30°."],
  },
  harmonium: {
    id: "harmonium", name: "Harmonium", family: "keyboard", origin: "indian_classical", accent: "indian", glyph: "🎹",
    blurb: "Hand-pumped bellows, one-octave keyboard. Heart of bhajans + qawwali + accompaniment.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "bellows", name: "Bellows", label: "Pump", description: "Left hand pumps continuously — the dynamic + sustaining engine." },
      { id: "drones", name: "Drone stops", label: "Drone", description: "Pulling stops produces sustained tonic + fifth drones." },
    ],
    sampleAudio: [{ id: "sa_sustain", label: "Sustained Sa with drone" }, { id: "bhajan", label: "Bhajan accompaniment" }],
    pedagogyTrackId: "harmonium_standard", difficultyFloor: 2,
    micSetupHints: ["Mic 30cm in front, slightly above keyboard height."],
  },
  mridangam: {
    id: "mridangam", name: "Mridangam", family: "perc_pitched", origin: "indian_classical", accent: "indian", glyph: "🥁",
    blurb: "South Indian barrel drum. Two heads, complementary pitches, the spine of Carnatic rhythm.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "right_head", name: "Valanthalai (right)", label: "Treble head", description: "Higher-pitched head — strikes Tha, Nam, Dhin, Dheem." },
      { id: "left_head", name: "Thoppi (left)", label: "Bass head", description: "Lower, pitch-bendable head — strikes Ghe, Thom." },
    ],
    sampleAudio: [{ id: "adi_tala", label: "Adi talam (8-beat cycle)" }],
    pedagogyTrackId: "mridangam_standard", difficultyFloor: 2,
    micSetupHints: ["Two mics ideal: one per head. Single mic: overhead between heads."],
  },
  veena: {
    id: "veena", name: "Veena", family: "fretted", origin: "indian_classical", accent: "indian", glyph: "🪕",
    blurb: "Ancient South Indian string instrument. Melodic strings + drones + sympathetic resonance.",
    tuningRef: { hz: 440, noteMap: "sa-based-C" },
    controls: [
      { id: "gamakam", name: "Gamakam pull", label: "Pitch pull", description: "Pulling a string laterally slides pitch — the signature Carnatic ornament." },
    ],
    sampleAudio: [{ id: "sa", label: "Sa" }, { id: "mayamalavagowla", label: "Mayamalavagowla phrase" }],
    pedagogyTrackId: "veena_standard", difficultyFloor: 3,
    micSetupHints: ["Mic near the dandi (neck) for melody; second mic at the yali (resonator) for bass."],
  },
  cello: {
    id: "cello", name: "Cello", family: "bowed", origin: "western", accent: "bowed", glyph: "🎻",
    blurb: "The baritone of the string family. Rich, resonant, close to the human voice.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "bow", name: "Bow", label: "Bow", description: "Down-bow vs up-bow alters phrasing; distance from bridge changes tone." },
      { id: "vibrato", name: "Vibrato", label: "Vibrato", description: "Left hand rocks to modulate pitch — wider + slower than violin." },
    ],
    sampleAudio: [{ id: "c2_open", label: "Open C2" }, { id: "bach_prelude", label: "Bach suite prelude" }],
    pedagogyTrackId: "cello_standard", difficultyFloor: 3,
    micSetupHints: ["Mic ~60cm in front, at bridge height."],
  },
  saxophone: {
    id: "saxophone", name: "Saxophone", family: "woodwind", origin: "western", accent: "bowed", glyph: "🎷",
    blurb: "Brass body, reed mouthpiece. The expressive jazz voice. Alto, tenor, soprano, baritone.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "embouchure", name: "Embouchure", label: "Lip + reed", description: "Lip pressure on reed controls tone + pitch. Loose = sub-tone; tight = bright." },
      { id: "alt_fingerings", name: "Alternate fingerings", label: "Alt fingers", description: "Multiple fingerings for a single note — used for intonation + trills." },
    ],
    sampleAudio: [{ id: "concert_a", label: "Concert A" }, { id: "blues_lick", label: "Blues lick" }],
    pedagogyTrackId: "saxophone_standard", difficultyFloor: 2,
    micSetupHints: ["Mic 15cm from the bell, angled slightly off-axis to avoid harshness."],
  },
  trumpet: {
    id: "trumpet", name: "Trumpet", family: "brass", origin: "western", accent: "bowed", glyph: "🎺",
    blurb: "Three valves, one brilliant voice. Lead in jazz, classical, mariachi.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "embouchure", name: "Embouchure + air", label: "Air + lips", description: "Higher notes = faster air + tighter lips. Most critical technique on any brass instrument." },
      { id: "mutes", name: "Mutes", label: "Mute", description: "Cup, straight, Harmon mutes change tone color dramatically." },
    ],
    sampleAudio: [{ id: "concert_bb", label: "Concert Bb" }, { id: "fanfare", label: "Fanfare" }],
    pedagogyTrackId: "trumpet_standard", difficultyFloor: 3,
    micSetupHints: ["Mic ~30cm from bell, slightly off-center to tame brashness."],
  },
  clarinet: {
    id: "clarinet", name: "Clarinet", family: "woodwind", origin: "western", accent: "bowed", glyph: "🎼",
    blurb: "Cylindrical bore, single reed. The most virtuosic woodwind — from Mozart to klezmer.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "register_key", name: "Register key", label: "Break", description: "The 'break' between low + upper registers — famously awkward to cross cleanly." },
      { id: "embouchure", name: "Embouchure", label: "Lip + reed", description: "Firm lower lip + controlled air column. Pitch bends with lip for jazz phrasing." },
    ],
    sampleAudio: [{ id: "concert_c", label: "Concert C (chalumeau)" }, { id: "klezmer", label: "Klezmer phrase" }],
    pedagogyTrackId: "clarinet_standard", difficultyFloor: 3,
    micSetupHints: ["Mic at the middle joint, not the bell — that's where tone lives."],
  },
  accordion: {
    id: "accordion", name: "Accordion", family: "keyboard", origin: "global", accent: "keyboard", glyph: "🪗",
    blurb: "Bellows + two keyboards + reeds. Parisian musette, Cajun, tango, polka, you name it.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "bellows", name: "Bellows", label: "Bellows", description: "Push + pull dynamics. Bellow shake = tremolo; pressure = volume." },
      { id: "bass_buttons", name: "Bass buttons", label: "Left hand", description: "Stradella bass system — single buttons play full chords." },
    ],
    sampleAudio: [{ id: "musette", label: "Parisian musette sample" }, { id: "tango", label: "Tango rhythm" }],
    pedagogyTrackId: "accordion_standard", difficultyFloor: 3,
    micSetupHints: ["Stereo pair: one mic each side. Solo mic: front, centered."],
  },
  synth: {
    id: "synth", name: "Synthesizer", family: "electronic", origin: "western", accent: "keyboard", glyph: "🎛️",
    blurb: "Electronic sound design + keyboard performance. From Moog to Prophet to modern soft synths.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "oscillator", name: "Oscillator", label: "Osc", description: "Saw, square, sine, triangle — the fundamental waveform." },
      { id: "filter", name: "Filter", label: "Filter", description: "Low-pass cutoff + resonance = the signature 'synthy' sweep." },
      { id: "envelope", name: "Envelope", label: "ADSR", description: "Attack, Decay, Sustain, Release — how a note shapes over time." },
    ],
    sampleAudio: [{ id: "bass_stab", label: "Bass stab (classic synth)" }, { id: "pad", label: "Warm pad" }],
    pedagogyTrackId: "synth_standard", difficultyFloor: 2,
    micSetupHints: ["Direct audio from line-out. MIDI controller + soft synth = ideal setup."],
  },
  dj_controller: {
    id: "dj_controller", name: "DJ controller", family: "electronic", origin: "western", accent: "keyboard", glyph: "🎧",
    blurb: "Two decks, a mixer, a crossfader. Beatmatching, cueing, phrasing — the DJ's craft.",
    tuningRef: { hz: 440, noteMap: "12-TET" },
    controls: [
      { id: "jog_wheels", name: "Jog wheels", label: "Jog", description: "Nudge + scratch control. The DJ's most intimate interface." },
      { id: "crossfader", name: "Crossfader", label: "Fade", description: "Blends the two decks. Sharp cuts vs slow fades vs scratching = signature styles." },
      { id: "eq_knobs", name: "3-band EQ", label: "EQ", description: "Bass / mid / treble kills + boosts for frequency-based transitions." },
    ],
    sampleAudio: [{ id: "beatmatch", label: "Beatmatched blend" }, { id: "scratch", label: "Baby scratch" }],
    pedagogyTrackId: "dj_standard", difficultyFloor: 2,
    micSetupHints: ["Direct audio from master out. Headphones required for cue monitoring."],
  },
};

export const listInstruments = () => Object.values(INSTRUMENTS);
export const getInstrument = (id: string) => INSTRUMENTS[id];
