import type { Lesson } from "./types";

export const LESSONS: Record<string, Lesson> = {
  piano_l1_01_hand_shape: {
    id: "piano_l1_01_hand_shape",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Hand shape & finding Middle C",
    objectives: [
      "Sit with a relaxed wrist, curved fingers",
      "Find Middle C on any piano (the C left of the two-black-key group nearest the name plate)",
      "Play C, D, E, F, G cleanly with fingers 1–5",
    ],
    writtenContent:
      "## Posture first\n\nSit tall. Feet flat. Elbows slightly above the keys. Your hand should look like it's gently holding a peach — curved, not flat.\n\n## Find Middle C\n\nLook at the keyboard. See the groups of two and three black keys? **Middle C is the white key immediately to the left of the two-black-key group closest to the piano's name.**\n\n## Play C–D–E–F–G\n\nPlace thumb (finger 1) on C, then a finger per white key. Press gently, count *one-and-two-and*. We'll go slow: 60 bpm.",
    audioRefs: [
      { id: "demo", label: "Your target (60 bpm)" },
      { id: "cmaj5_slow", label: "C-D-E-F-G, finger-by-finger" },
    ],
    exercisePlanId: "piano_l1_01_scale5",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.75, minPerDimension: { pitch: 0.8, rhythm: 0.6 } },
    estimatedMinutes: 8,
  },
  piano_l1_02_rhythm: {
    id: "piano_l1_02_rhythm",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Steady beat — quarters & halves",
    objectives: [
      "Clap quarter notes at 80 bpm with <50ms drift",
      "Hold a half note for exactly 2 beats",
      "Mix quarters and halves on one note (C)",
    ],
    writtenContent:
      "## The beat is a promise\n\nEvery quarter note is one click of the metronome. Every half note is two. We're not playing *faster*, we're playing *in time*.\n\nTap your foot with the metronome. Now play C on every tap. Now hold C for two taps. That's it — that's rhythm.",
    audioRefs: [{ id: "demo", label: "Target: 8 bars at 80 bpm" }],
    exercisePlanId: "piano_l1_02_quarter_halves",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 6,
  },
  piano_l1_03_twinkle: {
    id: "piano_l1_03_twinkle",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "First tune — Twinkle, Twinkle (right hand)",
    objectives: [
      "Play the melody of Twinkle using fingers 1–5 in C-position",
      "Keep steady tempo through bar 4",
      "Release cleanly between notes",
    ],
    writtenContent:
      "## You already know this tune\n\n*Twinkle, twinkle, little star* = C C G G A A G. *How I wonder what you are* = F F E E D D C. Your fingers don't move — only which finger presses changes.",
    audioRefs: [{ id: "demo", label: "Twinkle — whole tune, slow" }],
    exercisePlanId: "piano_l1_03_twinkle_rh",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 10,
  },
  piano_l1_04_left_hand: {
    id: "piano_l1_04_left_hand",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Adding the left hand — Twinkle bass",
    objectives: [
      "Find Middle C, then drop an octave to C3 for the left-hand thumb",
      "Play the bass line of Twinkle — same rhythm, lower octave",
      "Keep both hands relaxed; the left isn't louder than the right",
    ],
    writtenContent:
      "## One octave down\n\nYour left-hand thumb sits on **C3** — that's Middle C minus 12 keys (one octave down). Same finger numbers as the right hand but **mirrored**: finger 1 is still the thumb; finger 5 is the pinky, which now lives on the LEFT side.\n\n## The bass line\n\nIdentical rhythm to the right hand melody. Keep it quiet — the left hand is the foundation, not the roof.\n\n`C3 C3 G3 G3 A3 A3 G3 · F3 F3 E3 E3 D3 D3 C3`",
    audioRefs: [{ id: "demo", label: "Left-hand Twinkle, slow" }],
    exercisePlanId: "piano_l1_04_twinkle_lh",
    prerequisites: ["piano_l1_03_twinkle"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 8,
  },
  piano_l1_05_two_hands: {
    id: "piano_l1_05_two_hands",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Two hands together — full Twinkle",
    objectives: [
      "Play melody (RH) and bass (LH) simultaneously",
      "Keep steady tempo even when one hand is more interesting than the other",
      "Release both hands cleanly between phrases",
    ],
    writtenContent:
      "## The hardest thing in music\n\nThe first time you play two hands together, your brain will fight you. **That's normal.** Go stupid-slow — 40 bpm, one beat per breath if you need.\n\n## The secret\n\nDon't think about both hands at the same time. Think about the rhythm they share. When both hands land on beat 1, you only have to think about landing on beat 1.",
    audioRefs: [{ id: "demo", label: "Twinkle, both hands, 60 bpm" }],
    exercisePlanId: "piano_l1_05_twinkle_both",
    prerequisites: ["piano_l1_04_left_hand"],
    passCriteria: { minGradeOverall: 0.70 },
    estimatedMinutes: 12,
  },
  piano_l1_06_thumb_under: {
    id: "piano_l1_06_thumb_under",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Thumb under — the full C-major scale",
    objectives: [
      "Play C major one octave with fingering 1-2-3-1-2-3-4-5 ascending",
      "Thumb under for the 3→1 transition (on F going up, and F going down)",
      "Stay even — no gap when the thumb crosses",
    ],
    writtenContent:
      "## Why thumb-under exists\n\nYou have 5 fingers. The C-major scale has 8 notes. If you tried to use one finger per note, you'd run out after G. **Thumb-under** lets the same hand keep going smoothly up and down the keyboard forever.\n\n## The motion\n\nAscending: play E (finger 3), then sneak your thumb UNDER your hand to land on F (finger 1). Continue 2-3-4-5 up to C.\n\nDescending: play F (finger 1), then sneak finger 3 OVER your thumb to land on E. Continue down.\n\n## Even is everything\n\nIf you can hear the thumb-under, you're doing it too early or too late. The goal is invisible transitions.",
    audioRefs: [{ id: "demo", label: "C major scale, one octave, 80 bpm" }],
    exercisePlanId: "piano_l1_06_cmaj_scale",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { pitch: 0.8, rhythm: 0.7 } },
    estimatedMinutes: 10,
  },
  piano_l2_01_staff: {
    id: "piano_l2_01_staff",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Reading the treble staff",
    objectives: ["Name every line and space in treble clef", "Play a 4-bar sight-read", "Stay in time at 70 bpm"],
    writtenContent:
      "## The treble staff is 5 lines, 4 spaces\n\nLines from bottom up: **E G B D F** — mnemonic: *Every Good Boy Does Fine*.\nSpaces bottom up: **F A C E** — spells the word *FACE*.\n\nThat's the ENTIRE treble staff. Your right hand will read from this staff for the rest of your life.\n\n## Middle C sits just below\n\nThe bottom line of the treble staff is **E** (above Middle C). Middle C lives on a little 'ledger line' just underneath the staff.",
    audioRefs: [{ id: "demo", label: "Sight-read target · 4 bars, 70 bpm" }],
    exercisePlanId: "piano_l2_01_sightread",
    prerequisites: ["piano_l1_06_thumb_under"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 12,
  },
  piano_l2_02_bass_staff: {
    id: "piano_l2_02_bass_staff",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Reading the bass staff",
    objectives: [
      "Name every line and space in bass clef",
      "Play a 4-bar bass-line sight-read",
      "Switch between reading treble and bass within one piece",
    ],
    writtenContent:
      "## The bass staff is also 5 lines, 4 spaces\n\nLines bottom up: **G B D F A** — *Good Boys Do Fine Always*.\nSpaces bottom up: **A C E G** — *All Cows Eat Grass*.\n\nYour left hand will read from this staff.\n\n## Middle C sits just above\n\nThe top line of bass clef is A (below Middle C). Middle C lives on a ledger line right above the staff. So both staves share Middle C — they meet in the middle of the piano.",
    audioRefs: [{ id: "demo", label: "Bass-line sight-read, 70 bpm" }],
    exercisePlanId: "piano_l2_02_bass_sightread",
    prerequisites: ["piano_l2_01_staff"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  piano_l2_03_rests_ties: {
    id: "piano_l2_03_rests_ties",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Rests & ties — the silent parts matter",
    objectives: [
      "Recognize whole, half, and quarter rests on the staff",
      "Play a tied note as one sustained sound, not two separate ones",
      "Count accurately through silences",
    ],
    writtenContent:
      "## A rest is a note you can hear\n\nSilence in music isn't the absence of music — it's **part** of it. Rests come in the same values as notes:\n- Whole rest = 4 beats of silence (hangs below a line)\n- Half rest = 2 beats (sits on a line)\n- Quarter rest = 1 beat (the squiggly one)\n\nCount through rests just like through notes: *'one, two, THREE, four'* — the third beat is silent but still counted.\n\n## Ties are one note, not two\n\nA curved line connecting two same-pitch notes = hold the first through the second. Don't re-strike.",
    audioRefs: [{ id: "demo", label: "Rest + tie phrase" }],
    exercisePlanId: "piano_l2_03_rest_phrase",
    prerequisites: ["piano_l2_02_bass_staff"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 10,
  },
  piano_l2_04_accidentals: {
    id: "piano_l2_04_accidentals",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Sharps, flats, naturals — the black keys",
    objectives: [
      "Read a sharp (♯) as 'raise that note one key'",
      "Read a flat (♭) as 'lower that note one key'",
      "Understand a natural (♮) cancels a sharp or flat for the rest of the bar",
    ],
    writtenContent:
      "## The black keys have two names\n\nThe black key between C and D is both **C♯** (C-sharp) and **D♭** (D-flat). Same key, different name depending on the musical context.\n\n## An accidental lasts one bar\n\nWhen a sharp or flat appears before a note in a piece, it applies to **every repeat of that note in the same bar** — and resets at the barline. A natural sign (♮) cancels a sharp/flat mid-bar.\n\n## Sharps and flats are shortcuts\n\nRather than adding a sharp in front of every F in a piece, composers put a single ♯ at the start of each line (the 'key signature' — next lesson).",
    audioRefs: [{ id: "demo", label: "Phrase with sharps, flats, and naturals" }],
    exercisePlanId: "piano_l2_04_accidentals",
    prerequisites: ["piano_l2_03_rests_ties"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  piano_l2_05_key_sigs: {
    id: "piano_l2_05_key_sigs",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Key signatures — C, G, F",
    objectives: [
      "Recognize no sharps/flats = C major (or A minor)",
      "Recognize one sharp (F♯) = G major; one flat (B♭) = F major",
      "Apply the key signature to every note of that letter in the piece",
    ],
    writtenContent:
      "## The shortcut at the start\n\nAt the beginning of each staff line, composers write the **key signature** — a block of sharps or flats that apply to EVERY instance of those letter-name notes throughout the piece.\n\n- **No sharps/flats** = C major (all white keys)\n- **1 sharp (F♯)** = G major\n- **1 flat (B♭)** = F major\n\n## Why it matters\n\nInstead of littering the page with accidentals, the key signature declares 'play every F as F♯' once at the top. Your ear starts to expect the tonic (G, F, etc.) as home.",
    audioRefs: [{ id: "demo", label: "G major scale vs F major scale" }],
    exercisePlanId: "piano_l2_05_keysig_phrase",
    prerequisites: ["piano_l2_04_accidentals"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 12,
  },
  piano_l2_06_dynamics: {
    id: "piano_l2_06_dynamics",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Dynamics — loud, soft, and the shape between",
    objectives: [
      "Read p (piano) as soft, mf (mezzo-forte) as medium, f (forte) as loud",
      "Execute a crescendo (gradually louder) and decrescendo (gradually softer)",
      "Keep the rhythm steady even while the volume changes",
    ],
    writtenContent:
      "## Dynamics is the drama\n\nWithout volume contrast, music is robotic. Four core markings:\n- **pp** (pianissimo) = very soft\n- **p** (piano) = soft\n- **mf** (mezzo-forte) = medium-loud\n- **f** (forte) = loud\n- **ff** (fortissimo) = very loud\n\n## The shape between\n\nA **hairpin** opens toward the loud side. `<` = crescendo (get louder). `>` = decrescendo (get softer). The italic word *cresc.* or *dim.* means the same thing over a phrase.\n\n## Touch, not tension\n\nPlay loud by letting the weight of your arm fall into the key. Play soft by lifting slightly. Never by tensing your shoulder.",
    audioRefs: [{ id: "demo", label: "p → crescendo → f → decrescendo → p" }],
    exercisePlanId: "piano_l2_06_crescendo",
    prerequisites: ["piano_l2_05_key_sigs"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { dynamics: 0.7 } },
    estimatedMinutes: 10,
  },

  piano_l3_01_ode_to_joy: {
    id: "piano_l3_01_ode_to_joy",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Ode to Joy — first 8 bars",
    objectives: [
      "Play the main melody of Beethoven's Ode to Joy cleanly",
      "Hold the tempo steady at 90 bpm",
      "Phrase the two-bar groups naturally — breathe between them",
    ],
    writtenContent:
      "## Seven notes, one of humanity's most famous melodies\n\nBeethoven's 9th Symphony ends with a choir singing this tune. It uses only seven notes from the C major scale (E, D, F, G mostly) yet has carried meaning for two centuries.\n\n## The melody\n\n`E E F G · G F E D · C C D E · E D D`\n\nNotice the shape: steps up, a short descent, a long arc down, then the gentle fall. **Play it, then sing it in your head** — that's how you know if you're phrasing it right.",
    audioRefs: [{ id: "demo", label: "Ode to Joy, 8 bars, 90 bpm" }],
    exercisePlanId: "piano_l3_01_ode_melody",
    prerequisites: ["piano_l2_06_dynamics"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l3_02_amazing_grace: {
    id: "piano_l3_02_amazing_grace",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Amazing Grace — arranged in C major",
    objectives: [
      "Play the Amazing Grace melody in 3/4 (waltz feel)",
      "Observe the pickup note (anacrusis) correctly",
      "Let the long notes breathe — don't rush to the next phrase",
    ],
    writtenContent:
      "## The pickup is not beat 1\n\nAmazing Grace starts on beat 3 — a pickup into the first bar proper. Count 'one two **three**' and start on *three*. If you start on one, everything's off by two beats for the whole song.\n\n## 3/4 is a waltz\n\nThree beats per bar: **ONE** two three, **ONE** two three. The downbeats feel heavier — that's the pulse.\n\n## The long notes\n\nDotted halves last three beats. Hold them. They're the emotional center of every phrase.",
    audioRefs: [{ id: "demo", label: "Amazing Grace, one verse" }],
    exercisePlanId: "piano_l3_02_amazing_grace",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 12,
  },
  piano_l3_03_keertanam: {
    id: "piano_l3_03_keertanam",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "A Carnatic keertanam on piano — raga Mohanam on the white keys",
    objectives: [
      "Play a 4-bar keertanam phrase using Sa Ri2 Ga3 Pa Dha2 (C D E G A)",
      "Observe the gamaka-like ornament on Ga (slight slide from D to E)",
      "Feel the 8-beat adi tala cycle — 4 + 2 + 2",
    ],
    writtenContent:
      "## Indian classical on Western keys\n\nRaga Mohanam (the South Indian name for what's close to a major pentatonic) uses only 5 notes: **Sa Ri Ga Pa Dha** = **C D E G A** on piano. Five white keys, five different moods.\n\n## Our phrase\n\n`C D E G A G E D C · G E G D C` — a simple characteristic phrase of the raga.\n\n## The ornament\n\nIn Carnatic music, Ga (E) isn't just played — it's approached with a slight slide from the note below. On piano we can approximate this with a fast grace-note from D into E.",
    audioRefs: [{ id: "demo", label: "Mohanam phrase with gamaka approximation" }],
    exercisePlanId: "piano_l3_03_mohanam",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 15,
  },
  piano_l3_04_autumn_leaves: {
    id: "piano_l3_04_autumn_leaves",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Autumn Leaves — jazz standard head, simplified",
    objectives: [
      "Play the opening A-section melody of 'Autumn Leaves' in E minor",
      "Observe the descending shape — each phrase drops a step lower",
      "Feel the minor-key mood: melancholy but never sad-for-its-own-sake",
    ],
    writtenContent:
      "## Jazz starts here\n\n'Les Feuilles Mortes' (Autumn Leaves) is the most played jazz standard in the world. We learn the melody first — the harmony, chord-melody voicings, and improvisation come in L5.\n\n## The shape\n\n`A B C E · D F# G# B · C B A C · B A` — four phrases, each starting lower than the last. The descent is the song's emotional arc.\n\n## Minor feels different\n\nMinor doesn't mean sad. It means weighted, contemplative. Play it slowly, with space between phrases.",
    audioRefs: [{ id: "demo", label: "Autumn Leaves A-section, slow" }],
    exercisePlanId: "piano_l3_04_autumn_leaves",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 15,
  },
  piano_l3_05_hanon: {
    id: "piano_l3_05_hanon",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Hanon #1 — finger independence",
    objectives: [
      "Play Hanon exercise #1 right hand: C D F E F D E C + pattern shift up",
      "Keep all fingers equal in volume and timing",
      "Build to 90 bpm cleanly over a week",
    ],
    writtenContent:
      "## Hanon is boring. Do it anyway.\n\nCharles-Louis Hanon wrote 60 exercises in 1873 that every pianist still practices today. They're not music. They're gym for your fingers.\n\n## Exercise #1\n\nThe pattern: **C D F E F D E C** — then shift all notes up one step (D E G F G E F D) and repeat. Continue up through the C major scale.\n\n## Focus\n\n**Evenness** is the goal. Every finger strikes with equal volume and equal timing. If one finger is weaker, slow the metronome until it isn't.",
    audioRefs: [{ id: "demo", label: "Hanon #1, first pattern, 60 bpm" }],
    exercisePlanId: "piano_l3_05_hanon_1",
    prerequisites: ["piano_l2_06_dynamics"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { rhythm: 0.78, consistency: 0.75 } },
    estimatedMinutes: 10,
  },
  piano_l3_06_accompaniment: {
    id: "piano_l3_06_accompaniment",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Chord accompaniment — I-IV-V-I in C major",
    objectives: [
      "Play C, F, G, C as block chords in the left hand",
      "Hold each chord for 2 beats before changing",
      "Sing or hum a simple melody over the top",
    ],
    writtenContent:
      "## The progression that's everything\n\nI-IV-V-I is the chord progression under half of Western music: pop, rock, folk, blues, classical. In C major: **C → F → G → C**.\n\n## Building the chords\n\n- C = C + E + G (root + third + fifth)\n- F = F + A + C\n- G = G + B + D\n- Back to C\n\nLeft hand plays the chord; right hand can play or sing the melody.\n\n## Why it works\n\nThe V (G) 'wants' to resolve to the I (C) — that pull is the engine of nearly every phrase ending you've ever heard.",
    audioRefs: [{ id: "demo", label: "C F G C, 2 beats each, 80 bpm" }],
    exercisePlanId: "piano_l3_06_chord_progression",
    prerequisites: ["piano_l2_05_key_sigs"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 15,
  },

  piano_l4_01_g_major: {
    id: "piano_l4_01_g_major",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "G major scale, two octaves",
    objectives: [
      "Play G major from G3 to G5 — two full octaves — at 100 bpm",
      "Observe the F♯ (the one sharp in G major) both directions",
      "Smooth thumb-under at the octave crossover",
    ],
    writtenContent:
      "## Welcome to Pro tier\n\nYou earned your Standard Certificate. The difference at Pro: you don't just play in C major anymore — you play in ANY key.\n\n## G major has one sharp\n\nG A B C D E F♯ G. The F♯ is what makes it G major and not something else.\n\n## Fingering (right hand, ascending)\n\n1-2-3-1-2-3-4-5 up the first octave. Then the thumb sneaks under on the way through the second. Descending: reverse.\n\n## Both hands\n\nL4 = hands together on everything. The right hand starts on G3 thumb; the left hand starts on G2 pinky. Mirror images.",
    audioRefs: [{ id: "demo", label: "G major, two octaves, hands together, 100 bpm" }],
    exercisePlanId: "piano_l4_01_g_major_2oct",
    prerequisites: ["piano_l3_06_accompaniment"],
    passCriteria: { minGradeOverall: 0.75, minPerDimension: { pitch: 0.8, rhythm: 0.75 } },
    estimatedMinutes: 15,
  },
  piano_l4_02_d_major: {
    id: "piano_l4_02_d_major",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "D major scale, two octaves",
    objectives: [
      "Play D major (two sharps: F♯, C♯) two octaves hands together",
      "Apply the same thumb-under logic in a new key",
      "Build fluency at 110 bpm",
    ],
    writtenContent:
      "## Two sharps: F♯ and C♯\n\nD E F♯ G A B C♯ D. Notice: once you know which notes are sharp, the fingering stays identical to G major.\n\n## The pattern is the point\n\nEvery major scale has the same interval pattern: whole-whole-half-whole-whole-whole-half. Once your fingers know the pattern, you can play it in any starting key.",
    audioRefs: [{ id: "demo", label: "D major, hands together, 110 bpm" }],
    exercisePlanId: "piano_l4_02_d_major_2oct",
    prerequisites: ["piano_l4_01_g_major"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 10,
  },
  piano_l4_03_f_major: {
    id: "piano_l4_03_f_major",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "F major scale — your first flat key",
    objectives: [
      "Play F major (one flat: B♭) two octaves hands together",
      "Learn the F-major right-hand fingering (1-2-3-4-1-2-3-4)",
      "Understand why F major needs different fingering than C",
    ],
    writtenContent:
      "## One flat: B♭\n\nF G A B♭ C D E F. The B♭ is what makes it F major.\n\n## Fingering is different\n\nF major RH ascending: **1-2-3-4-1-2-3-4**. Because the B♭ is a black key, the thumb-under happens at a different spot than in C or G.\n\n## Left hand: 5-4-3-2-1-3-2-1\n\nStarts on F2 (pinky), the 3rd finger crosses over the thumb at the 5th note (C). Mirror of the RH thumb-under.",
    audioRefs: [{ id: "demo", label: "F major, hands together, 100 bpm" }],
    exercisePlanId: "piano_l4_03_f_major_2oct",
    prerequisites: ["piano_l4_01_g_major"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l4_04_a_minor: {
    id: "piano_l4_04_a_minor",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "A minor — your first minor scale",
    objectives: [
      "Play natural A minor two octaves (same notes as C major, different starting note)",
      "Recognize 'relative minor' — A minor and C major are partners",
      "Feel the difference in mood",
    ],
    writtenContent:
      "## Relative minor\n\nEvery major key has a relative minor — same notes, different tonal center. A minor uses **the same white keys as C major** but starts and rests on A.\n\nA B C D E F G A. Same keys as C major; different feeling.\n\n## Natural vs harmonic vs melodic\n\nThere are three versions of every minor scale — we learn **natural** first (above). Harmonic and melodic variants arrive in L5.\n\n## The dark sibling\n\nSame piano keys, different mood. That's the weirdness and beauty of modality.",
    audioRefs: [{ id: "demo", label: "A natural minor, two octaves, 90 bpm" }],
    exercisePlanId: "piano_l4_04_a_minor_2oct",
    prerequisites: ["piano_l4_01_g_major"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l4_05_arpeggios: {
    id: "piano_l4_05_arpeggios",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "Arpeggios — I, IV, V in C major, two octaves",
    objectives: [
      "Play C, F, G major arpeggios (root-3rd-5th-octave) two octaves",
      "Use fingering 1-2-3-5 (RH) and 5-3-2-1 (LH)",
      "Connect arpeggios smoothly — no gaps at the octave crossover",
    ],
    writtenContent:
      "## Arpeggios are chords spelled out\n\nA C major arpeggio: C E G C E G C — the chord tones in order, one at a time, across octaves. Foundation for all chord-based playing.\n\n## Three chords, three arpeggios\n\n- **C arpeggio**: C E G C E G C\n- **F arpeggio**: F A C F A C F\n- **G arpeggio**: G B D G B D G\n\nThese are the I-IV-V of C major — the same chords you accompanied with in L3.\n\n## Fingering\n\nRH: 1-2-3-5 and repeat. LH: 5-3-2-1 and repeat. Clean thumb-under at every octave.",
    audioRefs: [{ id: "demo", label: "C, F, G arpeggios, two octaves" }],
    exercisePlanId: "piano_l4_05_c_arpeggio",
    prerequisites: ["piano_l3_06_accompaniment"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l4_06_circle_of_fifths: {
    id: "piano_l4_06_circle_of_fifths",
    instrumentId: "piano",
    level: 4, tier: "pro",
    title: "Circle of fifths — the key map",
    objectives: [
      "Understand the circle of fifths as a map of all 12 major keys",
      "Play G→D→A→E major scales in sequence (4 sharps added)",
      "Recognize the flat side: F→B♭→E♭→A♭ (4 flats added)",
    ],
    writtenContent:
      "## The key map\n\nStart at C (0 sharps, 0 flats). Go up a fifth: G (1 sharp). Up another fifth: D (2 sharps). Continue: A, E, B, F♯, C♯.\n\nGo the OTHER direction: F (1 flat), B♭ (2 flats), E♭, A♭, D♭, G♭.\n\n## Why this matters\n\nThe circle of fifths tells you how 'far' any two keys are from each other. Modulating from C to G is one step — close, natural. Modulating from C to F♯ is six steps — distant, dramatic.\n\nEvery chord progression, every key change, every jazz standard lives on this circle.",
    audioRefs: [{ id: "demo", label: "C→G→D→A major scales in sequence" }],
    exercisePlanId: "piano_l4_06_circle_progression",
    prerequisites: ["piano_l4_01_g_major", "piano_l4_03_f_major"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 15,
  },

  piano_l5_01_triads: {
    id: "piano_l5_01_triads",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "Triads — major, minor, diminished, augmented",
    objectives: [
      "Build a triad by stacking thirds: root, 3rd, 5th",
      "Hear the four qualities: major (bright), minor (dark), dim (tense), aug (suspended)",
      "Play all four qualities rooted on C (C / Cm / Cdim / Caug)",
    ],
    writtenContent:
      "## A triad is three notes, one identity\n\nStack two thirds on any root note and you have a triad. The QUALITY of the thirds determines the chord's color:\n- **Major**: major 3rd + minor 3rd → bright, stable (C E G)\n- **Minor**: minor 3rd + major 3rd → dark, weighted (C E♭ G)\n- **Diminished**: minor 3rd + minor 3rd → tense, unstable (C E♭ G♭)\n- **Augmented**: major 3rd + major 3rd → floating, unresolved (C E G♯)\n\n## Play all four rooted on C\n\nHear the difference. Your ear is learning a new vocabulary — four 'colors' you can deploy deliberately from now on.",
    audioRefs: [{ id: "demo", label: "C major, C minor, C dim, C aug" }],
    exercisePlanId: "piano_l5_01_triads_on_c",
    prerequisites: ["piano_l4_05_arpeggios"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l5_02_inversions: {
    id: "piano_l5_02_inversions",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "Inversions — rearranging the triad",
    objectives: [
      "Play C major in root position (C E G), 1st inversion (E G C), 2nd inversion (G C E)",
      "Understand inversions = same notes, different bottom note",
      "Use inversions to connect chords with minimal hand motion",
    ],
    writtenContent:
      "## Same chord, different face\n\nThe C major triad has three notes: C, E, G. You can arrange them three ways:\n- **Root position**: C E G (root at bottom)\n- **1st inversion**: E G C (3rd at bottom)\n- **2nd inversion**: G C E (5th at bottom)\n\nAll three are 'C major chords'. The bottom note changes, which changes the color slightly, but the chord's identity is the same.\n\n## Why we use inversions\n\nPlaying C → F → G → C in root position means your hand jumps around. Using inversions (C root → F 2nd-inv → G 1st-inv → C root) lets your hand stay in one place. Smoother, faster, more musical.",
    audioRefs: [{ id: "demo", label: "C root → 1st inv → 2nd inv → root" }],
    exercisePlanId: "piano_l5_02_c_inversions",
    prerequisites: ["piano_l5_01_triads"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l5_03_pop_progression: {
    id: "piano_l5_03_pop_progression",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "The I-V-vi-IV progression — half of pop music",
    objectives: [
      "Play I (C) → V (G) → vi (Am) → IV (F) in C major",
      "Use smooth voice leading — connect with inversions when possible",
      "Recognize this as the backbone of thousands of pop songs",
    ],
    writtenContent:
      "## Four chords, infinite songs\n\nI-V-vi-IV is the most widely used chord progression in pop music. Let It Be, Don't Stop Believin', With or Without You, Someone Like You, and hundreds more sit on exactly these four chords.\n\n## In C major\n\n- **I** = C major (C E G)\n- **V** = G major (G B D)\n- **vi** = A minor (A C E) — lowercase = minor\n- **IV** = F major (F A C)\n\n## Voice leading\n\nPlay each chord in whatever inversion keeps the most notes COMMON between successive chords. Your hand barely moves — and the progression sounds smoother than the naive root-position version.",
    audioRefs: [{ id: "demo", label: "C → G → Am → F, four bars" }],
    exercisePlanId: "piano_l5_03_pop_prog",
    prerequisites: ["piano_l5_02_inversions"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 15,
  },
  piano_l5_04_alberti_bass: {
    id: "piano_l5_04_alberti_bass",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "Alberti bass — the breaking of chords",
    objectives: [
      "Play a left-hand Alberti bass pattern: bottom-top-middle-top, repeat",
      "Apply it to C major: C-G-E-G · F-C-A-C · G-D-B-D · C-G-E-G",
      "Keep the right-hand melody independent and on top",
    ],
    writtenContent:
      "## Mozart's favorite pattern\n\nAn Alberti bass (named after Domenico Alberti, 1710–1740) breaks a chord into a rippling arpeggio in the left hand while the right hand sings a melody. You've heard it in thousands of classical pieces.\n\n## The pattern\n\nTake a C major triad (C E G). Play it as: **bottom (C) → top (G) → middle (E) → top (G)**. Repeat four times before the chord changes.\n\n## Why it works\n\nThe Alberti bass is fuller than a single bass note but doesn't compete with the melody. The gentle ripple gives the piece motion without tumbling over the singing line on top.",
    audioRefs: [{ id: "demo", label: "Alberti bass under a C major melody" }],
    exercisePlanId: "piano_l5_04_alberti",
    prerequisites: ["piano_l5_03_pop_progression"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 15,
  },
  piano_l5_05_chord_melody: {
    id: "piano_l5_05_chord_melody",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "Chord-melody — one hand, two ideas",
    objectives: [
      "Play a simple melody with the right hand's top finger (5) while filling with chord tones below",
      "Keep the melody note always on top, consistent in volume",
      "Maintain the chord progression underneath without breaking the melodic line",
    ],
    writtenContent:
      "## The pianist's super-power\n\nWith 5 fingers per hand, you can play a melody AND its chord accompaniment simultaneously in one hand. This is how solo piano arrangements of any song work.\n\n## The rule: melody on top, always\n\nFinger 5 (pinky) plays the melody. The lower fingers fill in chord tones. When the melody note is within the chord, the chord is implied by the fill. When the melody note is outside the chord, the fill tone stays clearly below, in the harmony's register.\n\n## Simple example\n\nMelody: C→E→G. Chord: C major. In one hand: [C+E+C_pinky], [C+E+E_pinky], [C+E+G_pinky]. The pinky always sings the melody.",
    audioRefs: [{ id: "demo", label: "Simple chord-melody on Twinkle" }],
    exercisePlanId: "piano_l5_05_chord_melody",
    prerequisites: ["piano_l5_02_inversions"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 15,
  },
  piano_l5_06_seventh_chords: {
    id: "piano_l5_06_seventh_chords",
    instrumentId: "piano", level: 5, tier: "pro",
    title: "Seventh chords — Cmaj7, Cm7, C7",
    objectives: [
      "Build a 7th chord by stacking another third on top of a triad",
      "Hear the three core 7th flavors: maj7 (dreamy), m7 (cool jazz), 7/dominant (bluesy tension)",
      "Play Cmaj7 (C E G B), Cm7 (C E♭ G B♭), C7 (C E G B♭)",
    ],
    writtenContent:
      "## Four notes, much richer color\n\nA 7th chord adds a fourth note a third above the triad's 5th. That extra color transforms the chord from stable to interesting:\n\n- **Cmaj7** (C E G B): dreamy, floating, the ballad chord\n- **Cm7** (C E♭ G B♭): cool, jazz-standard, slightly melancholy\n- **C7** (C E G B♭): dominant — tense, bluesy, WANTS to resolve (usually to F)\n\n## Dominant 7 is the action chord\n\nC7 has a tritone inside it (E ↔ B♭). That dissonance is what creates the pull to the tonic. Without dominant 7 chords, there's no blues, no bebop, no gospel. Learn it.\n\n## Practice\n\nPlay all three on C, then move them to F (Fmaj7, Fm7, F7), then to G. Hands-together with L4-L5 arpeggio fingering.",
    audioRefs: [{ id: "demo", label: "Cmaj7 → Cm7 → C7" }],
    exercisePlanId: "piano_l5_06_seventh_chords",
    prerequisites: ["piano_l5_01_triads"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 15,
  },

  piano_l6_01_clementi: {
    id: "piano_l6_01_clementi",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Clementi Sonatina Op. 36 No. 1 — opening 8 bars",
    objectives: [
      "Play the right-hand melody of Clementi's Sonatina Op. 36 No. 1, mvt 1",
      "Keep the left-hand Alberti bass steady and quiet underneath",
      "Observe the dynamic markings (p, f, cresc.)",
    ],
    writtenContent:
      "## The beginner-classical standard\n\nMuzio Clementi (1752–1832) wrote six sonatinas specifically to teach. Op. 36 No. 1 is the most-played of any piano piece in the world after Für Elise — every aspiring pianist plays it.\n\n## The opening\n\nRight hand: **C E G C · E G C E · F D B G · E C G E** (8 bars). Classic Alberti pattern in the left.\n\n## The story\n\nThis is what you've been building toward since L1. The melody uses the C-major scales you learned, the left hand uses the Alberti pattern you just practiced, and the whole thing is a real piece of music written by a human ear — not an exercise.",
    audioRefs: [{ id: "demo", label: "Clementi Op. 36 No. 1 mvt 1 opening" }],
    exercisePlanId: "piano_l6_01_clementi_opening",
    prerequisites: ["piano_l5_04_alberti_bass"],
    passCriteria: { minGradeOverall: 0.76 },
    estimatedMinutes: 20,
  },
  piano_l6_02_chopin_emin: {
    id: "piano_l6_02_chopin_emin",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Chopin Prelude in E minor — opening (simplified)",
    objectives: [
      "Play the singing right-hand melody of Chopin's E minor Prelude",
      "Execute the descending left-hand chord pattern with quiet control",
      "Observe the expressive 'largo' tempo — slow and breathing",
    ],
    writtenContent:
      "## The first Chopin you'll ever play\n\nPrelude Op. 28 No. 4 in E minor is short, slow, and devastating. The right hand sings one long melodic line; the left hand walks downward through a chain of slightly-different chords.\n\n## Why it's a lesson\n\nChopin teaches you what 'expression' means on piano. There are no fast notes to hide behind. Every touch, every pedal press, every breath is exposed.\n\n## Start simple\n\nWe simplify the LH to block chords (not the original's suspended inner voices). The MELODY is what matters. Make it sing, even at 50 bpm.",
    audioRefs: [{ id: "demo", label: "Chopin Prelude in Em, simplified opening" }],
    exercisePlanId: "piano_l6_02_chopin_em",
    prerequisites: ["piano_l4_04_a_minor", "piano_l5_05_chord_melody"],
    passCriteria: { minGradeOverall: 0.74, minPerDimension: { dynamics: 0.7, consistency: 0.72 } },
    estimatedMinutes: 25,
  },
  piano_l6_03_evans_voicing: {
    id: "piano_l6_03_evans_voicing",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Bill Evans rootless voicings — ii-V-I in C",
    objectives: [
      "Play a rootless voicing over ii (Dm7): F-A-C-E (the 3-5-7-9)",
      "Connect to rootless V7 (G7): F-A-B-E",
      "Land on rootless Imaj7 (Cmaj7): E-G-B-D",
    ],
    writtenContent:
      "## The jazz piano revolution\n\nBill Evans (1929–1980) changed jazz piano by stripping the root out of his voicings. Why? Because in a trio, the bassist plays the root. The pianist's job is the COLORS — 3rds, 7ths, 9ths — which hold the chord's identity.\n\n## Rootless ii-V-I in C major\n\n- **Dm7** (ii): F A C E (3rd, 5th, 7th, 9th). No D in sight.\n- **G7** (V): F A B E (7th, 9th, 3rd, 13th). No G in sight.\n- **Cmaj7** (I): E G B D (3rd, 5th, 7th, 9th). No C in sight.\n\n## Notice the motion\n\nMost notes stay. One voice steps down a half-step at each chord change. That's called voice leading, and it's what makes these voicings sound so smooth.",
    audioRefs: [{ id: "demo", label: "Rootless ii-V-I in C, slow" }],
    exercisePlanId: "piano_l6_03_rootless_iivi",
    prerequisites: ["piano_l5_06_seventh_chords"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 20,
  },
  piano_l6_04_yaman_on_piano: {
    id: "piano_l6_04_yaman_on_piano",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Raga Yaman on piano — approximating the ornaments",
    objectives: [
      "Play a Yaman phrase: Sa → Ga → Ma♯ → Dha → Ni → Sa' (C → E → F♯ → A → B → C')",
      "Approximate the 'meend' (glide) with a fast chromatic fill between notes",
      "Keep the phrase unhurried — Indian classical breathes",
    ],
    writtenContent:
      "## Yaman on a Western instrument\n\nRaga Yaman uses Lydian-like notes: Sa Re Ga **Ma♯** Pa Dha Ni Sa'. On piano in C: **C D E F♯ G A B C'**. One sharp — F♯ — distinguishes it from regular major.\n\n## A characteristic phrase\n\n`C E F♯ A B C'` ascending, resting on the high C'. Notice the skip between C (Sa) and E (Ga) — Yaman often leaves out Re in ascent.\n\n## The meend\n\nOn a sitar, the meend is a glide between notes. On piano, we approximate with a fast chromatic fill: instead of C→E, play C C♯ D D♯ E as a grace run.\n\n## The mood\n\nYaman is an evening raga — contemplative, tender. Don't play fast.",
    audioRefs: [{ id: "demo", label: "Yaman phrase with approximated meend" }],
    exercisePlanId: "piano_l6_04_yaman_phrase",
    prerequisites: ["piano_l3_03_keertanam"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 18,
  },
  piano_l6_05_hanon_stretched: {
    id: "piano_l6_05_hanon_stretched",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Hanon exercises 20–30 — stretched patterns",
    objectives: [
      "Play Hanon exercise #20 at 100 bpm cleanly, both hands",
      "Build strength in the 4th and 5th fingers specifically",
      "Keep wrists relaxed — tension invites injury at higher tempos",
    ],
    writtenContent:
      "## The late Hanon exercises\n\nExercises 20-30 target finger independence at higher speeds. The patterns stretch across more of the keyboard and require real finger strength.\n\n## Warnings\n\nIf your wrist ever hurts, STOP. Hanon injury is real. Ten minutes at 80 bpm beats thirty minutes at 120 bpm if the fast version tenses you.\n\n## The goal at L6\n\nExercise #20 clean at 100 bpm. That's the gate for Pro Certificate practical. Build slowly — 60 → 70 → 80 → 90 → 100 over weeks.",
    audioRefs: [{ id: "demo", label: "Hanon #20, 100 bpm" }],
    exercisePlanId: "piano_l6_05_hanon_20",
    prerequisites: ["piano_l3_05_hanon"],
    passCriteria: { minGradeOverall: 0.75, minPerDimension: { rhythm: 0.8, consistency: 0.78 } },
    estimatedMinutes: 15,
  },
  piano_l6_06_sightread_g5: {
    id: "piano_l6_06_sightread_g5",
    instrumentId: "piano", level: 6, tier: "pro",
    title: "Sight-read a grade-5 level unseen piece",
    objectives: [
      "Read a 16-bar piece you've never seen before",
      "Play it at 70 bpm with correct notes and rhythm",
      "Don't stop when you make a mistake — keep moving",
    ],
    writtenContent:
      "## The sight-reading discipline\n\nAt the Pro tier, you should be able to sit down at any piano, open any beginner/intermediate book, and PLAY the first page of anything. Not perfectly — but readably.\n\n## How to sight-read\n\n1. **Scan first**: look at the key signature, time signature, tempo, and general shape BEFORE you play a note.\n2. **Count out loud**: the rhythm is the skeleton. Get it right, even if you miss pitches.\n3. **Don't stop for mistakes**: keep the pulse. Stopping to correct breaks the sight-read. Fix errors on a second pass.\n\n## The Pro Certificate gate\n\nThis exercise is part of the Pro Certificate practical. Pass it → unlock L7 (Genius tier).",
    audioRefs: [{ id: "demo", label: "Target performance of the unseen piece" }],
    exercisePlanId: "piano_l6_06_unseen_piece",
    prerequisites: ["piano_l6_01_clementi", "piano_l6_03_evans_voicing"],
    passCriteria: { minGradeOverall: 0.75, minPerDimension: { pitch: 0.78, rhythm: 0.78 } },
    estimatedMinutes: 20,
  },

  guitar_l1_01_hold: {
    id: "guitar_l1_01_hold",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Holding the guitar & your first string",
    objectives: [
      "Sit or stand with the guitar's body flat against you, neck angled up slightly",
      "Identify the 6 strings by letter (low to high: E A D G B E)",
      "Pluck each open string cleanly and hear its pitch",
    ],
    writtenContent:
      "## The guitar is an armful\n\nBody flat against your ribs. Neck tilted up at about 10–15° — not pointing at the floor, not pointing at the ceiling. If your wrist hurts after 5 minutes, your posture is wrong; adjust before you continue.\n\n## Six strings, two Es\n\nFrom the thickest string (closest to your face) to the thinnest: **E - A - D - G - B - E**. The two Es are two octaves apart — low E2 and high E4. The rest run: A2, D3, G3, B3.\n\n## Just pluck\n\nWith your thumb or a pick, sound each open string one by one. Listen. A clean open string rings — if it buzzes, your finger is accidentally touching a fret.",
    audioRefs: [{ id: "demo", label: "Six open strings, low to high" }],
    exercisePlanId: "guitar_l1_01_open_strings",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.65 },
    estimatedMinutes: 8,
  },
  guitar_l1_02_first_fret: {
    id: "guitar_l1_02_first_fret",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Your first fretted notes — the low E string",
    objectives: [
      "Press down just behind each fret (not on it, not in the middle)",
      "Play E (open) → F (1st fret) → G (3rd fret) → A (5th fret)",
      "Keep each note clean and ringing",
    ],
    writtenContent:
      "## Where to press\n\nThe fret itself is the metal bar. Press the string **just behind** the fret (on the headstock side) — not on the metal, not way back. Close to the fret = clean note with minimal pressure.\n\n## Four notes on one string\n\nLow E string: open = E · 1st fret = F · 3rd fret = G · 5th fret = A. That's the bottom half of an A-minor scale without moving to another string.",
    audioRefs: [{ id: "demo", label: "E · F · G · A on low E string" }],
    exercisePlanId: "guitar_l1_02_e_string_walk",
    prerequisites: ["guitar_l1_01_hold"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.75 } },
    estimatedMinutes: 10,
  },
  guitar_l1_03_first_chord: {
    id: "guitar_l1_03_first_chord",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "First chord — Em",
    objectives: [
      "Fret E minor: 2nd fret of the A and D strings, fingers 2 and 3",
      "Strum all six strings cleanly",
      "Release and re-fret 5 times in a row without buzzing",
    ],
    writtenContent:
      "## E minor, the welcoming chord\n\nEm uses just two fretted notes: **finger 2 on the 2nd fret of A**, **finger 3 on the 2nd fret of D**. Every other string rings open.\n\n## The strum\n\nRelax your pick hand. Let the pick fall through all 6 strings — don't stab, don't scrape. A full Em should sound lush; if it buzzes, check your finger tips aren't touching neighboring strings.",
    audioRefs: [{ id: "demo", label: "Em chord — strum x4" }],
    exercisePlanId: "guitar_l1_03_em_strum",
    prerequisites: ["guitar_l1_02_first_fret"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  guitar_l1_04_g_chord: {
    id: "guitar_l1_04_g_chord",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Second chord — G major",
    objectives: [
      "Fret G major: finger 2 on 3rd fret of E (low), finger 3 on 3rd fret of B, finger 4 on 3rd fret of high E",
      "Play all six strings; D and G ring open",
      "Switch cleanly between Em and G without losing the beat",
    ],
    writtenContent:
      "## Your second chord\n\nG major is the companion to Em — they share many strings and live next to each other on the fretboard. Three fingers, three frets:\n\n- **Finger 2** — 3rd fret of the low E string\n- **Finger 3** — 2nd fret of the A string\n- **Finger 4** — 3rd fret of the high E string\n\nThe D, G, and B strings ring open.\n\n## The switch is everything\n\nHold Em. Without looking, reshape to G in one motion. Strum. Switch back to Em. Goal: **4 switches per 10 seconds** without buzz.",
    audioRefs: [{ id: "demo", label: "Em → G → Em → G, each strum 2 beats" }],
    exercisePlanId: "guitar_l1_04_em_g_switch",
    prerequisites: ["guitar_l1_03_first_chord"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 12,
  },
  guitar_l1_05_strum_pattern: {
    id: "guitar_l1_05_strum_pattern",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Your first strum pattern — Down-Down-Up-Up-Down",
    objectives: [
      "Keep the strum hand moving in a steady pendulum — downstrokes on the beat, upstrokes between",
      "Execute the D-D-U-U-D pattern cleanly on Em for 8 bars",
      "Feel the groove: the missing strum on '3' (an 'air stroke' — hand moves, doesn't hit strings)",
    ],
    writtenContent:
      "## The hand never stops\n\nThe secret of every guitarist's strum is that the hand **keeps moving** whether or not it's hitting strings. Downstrokes happen on the beat; upstrokes between. Your hand is a metronome with a pick in it.\n\n## The pattern\n\n**1** (D) — **2** (D) — **&** (U) — **3** (air) — **&** (U) — **4** (D)\n\nThat's the D-D-U-U-D pattern you've heard in thousands of songs. The trick is the 'air stroke' on beat 3 — your hand does a downward motion but doesn't touch the strings, then comes back up for the 'U'.\n\n## Practice on Em\n\nJust Em for now. Loop the pattern until your strum hand moves without conscious thought.",
    audioRefs: [{ id: "demo", label: "D-D-U-U-D on Em, 80 bpm" }],
    exercisePlanId: "guitar_l1_05_strum_em",
    prerequisites: ["guitar_l1_03_first_chord"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 15,
  },
  guitar_l1_06_first_song: {
    id: "guitar_l1_06_first_song",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Your first song — 'Horse With No Name' (Em / D6add9)",
    objectives: [
      "Play a full song using just Em and D6add9 (a movable shape — like Em but finger 2 on 3rd string)",
      "Switch between the two chords every 2 beats",
      "Apply the D-D-U-U-D strum pattern from L1.5",
    ],
    writtenContent:
      "## Two chords, one song\n\nAmerica's 'A Horse With No Name' (1971) uses only two chords for the entire song. They're both Em shapes:\n\n- **Em** (as you know it)\n- **D6add9** — Em shape but move finger 2 from 3rd fret of G to 3rd fret of D\n\nFor 4-minutes-plus, you alternate those two every 2 beats. That's the whole song.\n\n## Why this is the perfect first song\n\nYou already know Em. The second chord is a tiny finger movement. Apply your strum pattern — and you're playing a famous song in L1. That's the win.",
    audioRefs: [{ id: "demo", label: "Horse With No Name verse, 4 bars" }],
    exercisePlanId: "guitar_l1_06_horse_chords",
    prerequisites: ["guitar_l1_04_g_chord", "guitar_l1_05_strum_pattern"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 15,
  },

  violin_l1_01_hold: {
    id: "violin_l1_01_hold",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "Holding the violin & bowing an open string",
    objectives: [
      "Rest the violin on your collarbone; chin gently on the rest — not clamped",
      "Hold the bow with a relaxed grip: thumb curved, pinky on top, hair angled toward the bridge",
      "Draw a straight bow on the open A string for a clean, singing tone (4 seconds)",
    ],
    writtenContent:
      "## Where the violin lives\n\nThe violin's **body** rests on your collarbone. Your chin sits on the chinrest — **gently**. If your shoulder is raised or your neck is straining, you're holding it wrong; take it off, shake out, try again.\n\n## The bow is a breath\n\nBow grip: thumb curved like a hook, pinky balanced on top of the stick, other fingers draped. The bow moves parallel to the bridge — not swinging in an arc. A straight bow = a straight tone.\n\n## Your first note\n\nBow the open **A string** — that's the second-highest string. No fingers touching the fingerboard yet. Down-bow from frog to tip, slowly, 4 seconds. Then up-bow back. Clean tone, no scratching.",
    audioRefs: [{ id: "demo", label: "Open A, 4-second down-bow + up-bow" }],
    exercisePlanId: "violin_l1_01_open_a",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.65, minPerDimension: { tone: 0.65 } },
    estimatedMinutes: 10,
  },
  violin_l1_02_first_finger: {
    id: "violin_l1_02_first_finger",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "First finger — playing B on the A string",
    objectives: [
      "Curl your first finger onto the A string about one inch from the nut",
      "Press firmly enough to stop the string cleanly; don't squeeze",
      "Bow the result: it should sound a whole step up from A — that's B",
    ],
    writtenContent:
      "## Intonation is everything\n\nThe violin has **no frets**. There's no 'right' spot — there's only 'in tune' and 'not in tune'. Your ear is the only judge. Start by listening to a reference B, then try to match it.\n\n## Where the finger goes\n\nLook at the fingerboard. About **one inch from the nut** (the bone at the top where the strings begin), press your first finger down firmly. Keep it curved, not flat. Bow slowly — if you hear a clean note, you found B. If it's buzzing, press harder or move slightly.",
    audioRefs: [{ id: "demo", label: "B on A string — reference tone" }],
    exercisePlanId: "violin_l1_02_a_to_b",
    prerequisites: ["violin_l1_01_hold"],
    passCriteria: { minGradeOverall: 0.68, minPerDimension: { pitch: 0.7 } },
    estimatedMinutes: 10,
  },
  violin_l1_03_first_phrase: {
    id: "violin_l1_03_first_phrase",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "First phrase — A B C♯ D (D-major tetrachord)",
    objectives: [
      "Add finger 2 (C♯) and finger 3 (D) on the A string",
      "Play the four notes as a rising phrase, clean intonation",
      "Keep the bow steady — one note per bow stroke",
    ],
    writtenContent:
      "## Four notes, one bow each\n\nA (open) → B (finger 1) → C♯ (finger 2) → D (finger 3). That's a **tetrachord** — the lower half of a D major scale.\n\nFinger 2 sits **close to** finger 1 (only a half-step gap feels tight, but this is a whole step — about an inch). Finger 3 is a half-step from finger 2 — fingers almost touching.\n\n## Listen as you play\n\nIf the note sounds 'off', it IS off. Move the finger a millimeter. This is the whole game of violin — listen, adjust, repeat.",
    audioRefs: [{ id: "demo", label: "A B C# D rising, 60 bpm" }],
    exercisePlanId: "violin_l1_03_d_tetrachord",
    prerequisites: ["violin_l1_02_first_finger"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.72 } },
    estimatedMinutes: 12,
  },
  violin_l1_04_d_string: {
    id: "violin_l1_04_d_string",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "Adding the D string — fingers 1, 2, 3 on D",
    objectives: [
      "Bow open D cleanly",
      "Add finger 1 (E), finger 2 (F♯), finger 3 (G) on the D string",
      "Play the four notes as a rising phrase: D E F♯ G",
    ],
    writtenContent:
      "## D is a new world\n\nEverything you learned on the A string transfers to D — same finger positions, same whole/half step patterns, just a lower-pitched starting note.\n\n## D major tetrachord on the D string\n\n**D (open) → E (finger 1) → F♯ (finger 2) → G (finger 3)**. That's the lower tetrachord of D major — same intervals as A B C♯ D on the A string.\n\n## What you can do now\n\nYou have D E F♯ G on the D string AND A B C♯ D on the A string. That's **a full D major scale across two strings**. Put them together and you've played your first scale on violin.",
    audioRefs: [{ id: "demo", label: "D E F♯ G rising, 60 bpm" }],
    exercisePlanId: "violin_l1_04_d_tetrachord",
    prerequisites: ["violin_l1_03_first_phrase"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.72 } },
    estimatedMinutes: 12,
  },
  violin_l1_05_cross_string: {
    id: "violin_l1_05_cross_string",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "Cross-string bowing — D and A strings",
    objectives: [
      "Play D open → A open → D open → A open with smooth bow direction changes",
      "Tilt the bow slightly (not rotate) to cross between strings",
      "Keep the tone even on both strings",
    ],
    writtenContent:
      "## Not a wrist, an elbow\n\nTo cross from D to A, lift your bow ARM (from the elbow) — don't rotate your wrist. Your wrist stays relaxed; the elbow does the work.\n\n## Alternating open strings\n\n`D A D A` — eight counts, four down-bows, four up-bows. If you can hear a 'click' when you cross, you're moving too fast; smooth out the transition.\n\n## Why this matters\n\nEvery scale that spans more than one string, every arpeggio, every chord on violin needs cross-string control. Master it at 60 bpm and it'll serve you for years.",
    audioRefs: [{ id: "demo", label: "Cross-string D-A-D-A, 60 bpm" }],
    exercisePlanId: "violin_l1_05_cross_strings",
    prerequisites: ["violin_l1_04_d_string"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { tone: 0.7 } },
    estimatedMinutes: 12,
  },
  violin_l1_06_first_tune: {
    id: "violin_l1_06_first_tune",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "Your first tune — 'Mary Had a Little Lamb' on the A string",
    objectives: [
      "Play the melody of Mary Had a Little Lamb using only fingers on the A string",
      "Keep the bow steady — one note per bow stroke",
      "Phrase the two halves: question (bars 1-2) and answer (bars 3-4)",
    ],
    writtenContent:
      "## A tune you already know\n\n*Mary had a little lamb* uses just three notes on the A string:\n\n- **B** (finger 1)\n- **A** (open)\n- **C♯** (finger 2)\n\n## The melody\n\n`B A G A | B B B - | A A A - | B B B -`\nWait — for violin L1 let's simplify to the A-string-only version: `B A A B | B B B - | A A A - | B B B -`\n\nOne finger moves at a time. No cross-string. Just fingers 0/1/2 on A and a steady bow. You're playing your first recognisable melody on the violin.",
    audioRefs: [{ id: "demo", label: "Mary Had a Little Lamb, A-string version" }],
    exercisePlanId: "violin_l1_06_mary_lamb",
    prerequisites: ["violin_l1_03_first_phrase"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.72 } },
    estimatedMinutes: 15,
  },

  drums_l1_01_grip: {
    id: "drums_l1_01_grip",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Grip, posture, and your first strokes",
    objectives: [
      "Hold sticks with a matched grip — thumb and index form the fulcrum, other fingers loose",
      "Sit with your kick-drum foot flat, hi-hat foot on its pedal, snare between your knees",
      "Strike the snare four times at 80 bpm — equal volume, equal spacing",
    ],
    writtenContent:
      "## The stick is a pendulum\n\nHold lightly. The stick should bounce off the drum, not be forced into it. If your forearms are tense, you're gripping too hard.\n\n## Matched grip\n\nBoth hands the same: thumb pad on one side of the stick, index finger on the other, forming a pinch (the 'fulcrum'). Other three fingers drape underneath — they guide, they don't grip.\n\n## First strokes\n\n4 snare hits at 80 bpm. Goal: each hit sounds identical. If they don't, you're gripping inconsistently.",
    audioRefs: [{ id: "demo", label: "4 snare hits, 80 bpm" }],
    exercisePlanId: "drums_l1_01_snare_4",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 8,
  },
  drums_l1_02_kick_snare: {
    id: "drums_l1_02_kick_snare",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "The backbeat — kick on 1&3, snare on 2&4",
    objectives: [
      "Play kick on beats 1 and 3, snare on beats 2 and 4",
      "Keep both feet and hands relaxed — no stomping the kick",
      "Loop it for 8 bars without breaking tempo",
    ],
    writtenContent:
      "## The most important pattern in popular music\n\nKick-1, snare-2, kick-3, snare-4. Repeat forever. Half the world's music sits on this foundation.\n\n## The kick is quiet\n\nDon't stomp. A controlled heel-up motion gives you power and evenness. The drum does the work; your leg is a lever.\n\n## Count out loud\n\nSeriously — say **'ONE two THREE four'** while you play. Your mouth locks in the timing that your limbs are still learning.",
    audioRefs: [{ id: "demo", label: "Backbeat loop, 8 bars @ 80 bpm" }],
    exercisePlanId: "drums_l1_02_backbeat",
    prerequisites: ["drums_l1_01_grip"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  drums_l1_03_hihat: {
    id: "drums_l1_03_hihat",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Add the hi-hat — your first full groove",
    objectives: [
      "Add closed hi-hat on every quarter note (1 2 3 4)",
      "Keep kick and snare from L1.2 pattern intact underneath",
      "Play 8 bars — three limbs, one tempo",
    ],
    writtenContent:
      "## Three limbs, one rhythm\n\nRight hand plays hi-hat on every beat: 1, 2, 3, 4. Left hand plays snare on 2 and 4. Right foot plays kick on 1 and 3. Left foot stays on the hi-hat pedal, keeping it closed.\n\nIf your brain protests, that's normal. Go slower — 60 bpm, even 50. **Coordination is a physical skill, not a musical one**. It will come.",
    audioRefs: [{ id: "demo", label: "Full rock groove, 8 bars @ 80 bpm" }],
    exercisePlanId: "drums_l1_03_full_groove",
    prerequisites: ["drums_l1_02_kick_snare"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 12,
  },
  drums_l1_04_8th_hihat: {
    id: "drums_l1_04_8th_hihat",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Hi-hat on 8th notes — doubling the density",
    objectives: [
      "Play hi-hat on every 8th note (1 & 2 & 3 & 4 &) instead of quarters",
      "Keep kick on 1&3, snare on 2&4 exactly as before",
      "Hold the groove for 8 bars at 70 bpm without losing the feel",
    ],
    writtenContent:
      "## More hi-hat, same everything else\n\nThe backbeat you learned (kick 1&3, snare 2&4) stays exactly the same. What changes: instead of hi-hat on quarters, play 8th notes — twice as many hits.\n\n## Count with '&'\n\n`1 & 2 & 3 & 4 &` — eight hi-hat hits per bar. Kick on 1 and 3. Snare on 2 and 4.\n\n## Why go slower\n\nCounter-intuitively, start slower (70 bpm, not 80). More hi-hat hits means more opportunities for timing to drift. Tight at 70 first, then speed up.",
    audioRefs: [{ id: "demo", label: "8th-note hi-hat groove, 70 bpm" }],
    exercisePlanId: "drums_l1_04_8th_groove",
    prerequisites: ["drums_l1_03_hihat"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { rhythm: 0.78 } },
    estimatedMinutes: 12,
  },
  drums_l1_05_crash_accent: {
    id: "drums_l1_05_crash_accent",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Crash on 1 — announcing a new phrase",
    objectives: [
      "Replace the hi-hat on beat 1 of a new 4-bar phrase with a crash cymbal hit",
      "Let the crash ring — don't choke it",
      "Keep the kick and snare exactly as before",
    ],
    writtenContent:
      "## The crash is punctuation\n\nWhen a new section of a song starts, drummers hit the crash on beat 1 to mark the arrival. It says: 'something new is happening now.'\n\n## How to do it\n\nWherever you're about to start a new 4-bar phrase, replace the hi-hat on beat 1 with a crash on the same beat. The kick still hits on 1 underneath. Everything else continues.\n\n## Don't choke it\n\nAmateur drummers crash then grab the cymbal to stop it ringing. Don't. Let it ring — the decay is part of the sound.",
    audioRefs: [{ id: "demo", label: "Crash on 1 every 4 bars, full groove" }],
    exercisePlanId: "drums_l1_05_crash_on_one",
    prerequisites: ["drums_l1_04_8th_hihat"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  drums_l1_06_first_fill: {
    id: "drums_l1_06_first_fill",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Your first fill — a 1-bar tom fill into a phrase change",
    objectives: [
      "Play 3 bars of the regular groove, then a 1-bar fill, then start again with a crash on 1",
      "Fill with tom-tom 16th notes: T1 T1 T2 T2 T3 T3 — build down the kit",
      "Land back on beat 1 with the crash — don't rush into it",
    ],
    writtenContent:
      "## The fill is a breath\n\nA drum fill is a short break in the groove — usually the last bar of a 4-bar phrase — that announces the next section. It's like a singer taking a breath before a new verse.\n\n## The simplest fill\n\nLast bar of a 4-bar phrase: stop the groove. Play 16th notes across the toms: `T1 T1 T2 T2 T3 T3` — build DOWN the kit (high tom to floor tom). On beat 1 of the next bar, CRASH + kick to start the new phrase.\n\n## Don't overplay\n\nAt L1, keep fills to 1 bar. Shorter is almost always better. A great fill builds anticipation; a bad fill just fills space.",
    audioRefs: [{ id: "demo", label: "3 bars groove + 1 bar tom fill + crash on 1" }],
    exercisePlanId: "drums_l1_06_tom_fill",
    prerequisites: ["drums_l1_05_crash_accent"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 15,
  },

  sitar_l1_01_sa: {
    id: "sitar_l1_01_sa",
    instrumentId: "sitar",
    level: 1, tier: "standard",
    title: "Finding Sa & tuning the drone",
    objectives: [
      "Identify Sa (tonic) and Pa (fifth) on the main string",
      "Set the tanpura / drone to match",
      "Sustain a clean Sa for 10 seconds with the mizrab",
    ],
    writtenContent:
      "## Sa is home\n\nBefore any raga, there is Sa. It's the tonic, the anchor, the first breath of every phrase. The drone — tanpura or keyboard drone — gives you Sa and Pa forever. Listen first, play second.\n\n## Your mizrab\n\nWire plectrum, right index finger. Down-stroke = **Da**. Up-stroke = **Ra**. For Sa, just Da. Clean. Ringing. Ten seconds.",
    audioRefs: [{ id: "drone", label: "Tanpura drone in C" }, { id: "sa_demo", label: "Guruji plays Sa" }],
    exercisePlanId: "sitar_l1_01_sustain_sa",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.8, tone: 0.65 } },
    estimatedMinutes: 10,
  },
  sitar_l4_01_yaman_alap: {
    id: "sitar_l4_01_yaman_alap",
    instrumentId: "sitar",
    level: 4, tier: "pro",
    title: "Raga Yaman — opening alap with meend",
    objectives: [
      "Sustain Sa then climb to Ga cleanly",
      "Execute meend from Ma down to Ga",
      "Breathe at the end of each phrase",
    ],
    writtenContent:
      "## The evening raga\n\nYaman is the gentlest welcome to Hindustani classical. Thaat: Kalyan. Vadi: Ga. Samvadi: Ni. Time: early evening.\n\n**Aaroha:** Ni Re Ga Ma Dha Ni Sa'  \n**Avaroha:** Sa' Ni Dha Pa Ma Ga Re Sa  \n**Pakad:** Ni Re Ga, Ma Dha Ni Sa'\n\nStart on Sa. Breathe. Climb slowly to Ga. From Ma, bend (meend) down to Ga in one continuous motion — that's the heart of Yaman.",
    audioRefs: [{ id: "demo", label: "Ustad's alap in Yaman" }],
    exercisePlanId: "sitar_l4_01_yaman_meend",
    prerequisites: ["sitar_l1_01_sa"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { pitch: 0.75, tone: 0.7 } },
    estimatedMinutes: 15,
  },

  tabla_l1_01_dha: {
    id: "tabla_l1_01_dha",
    instrumentId: "tabla",
    level: 1, tier: "standard",
    title: "Your first bol — Dha",
    objectives: [
      "Strike Dha cleanly — right finger on the syahi + left hand open",
      "Produce a ringing, pitched sound",
      "Repeat 16 times on the beat at 80 bpm",
    ],
    writtenContent:
      "## Dha = Dha + Ge\n\n**Dha** is the sound of both hands together: Dha (right, ringing open stroke on the dayan) + Ge (left, open palm slap on the bayan). It's the first bol of teentaal.\n\nGet one clean Dha. Then 16 in a row.",
    audioRefs: [{ id: "demo", label: "Guruji plays 16x Dha" }],
    exercisePlanId: "tabla_l1_01_dha_16",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 8,
  },
};

export const listLessonsForInstrument = (instrumentId: string) =>
  Object.values(LESSONS)
    .filter((l) => l.instrumentId === instrumentId)
    .sort((a, b) => a.level - b.level);

export const getLesson = (id: string) => LESSONS[id];
