import type { Lesson } from "./types";

export const LESSONS: Record<string, Lesson> = {
  piano_l1_01_hand_shape: {
    id: "piano_l1_01_hand_shape",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Hand shape & finding Middle C",
    objectives: [
      "Sit with a relaxed wrist, curved fingers",
      "Find Middle C on any piano (the C left of the two-black-key group nearest the name plate)",
      "Play C, D, E, F, G cleanly with fingers 1–5",
    ],
    writtenContent:
      "## Posture first\n\nSit tall. Feet flat. Elbows slightly above the keys. Your hand should look like it's gently holding a peach — curved, not flat.\n\n## Find Middle C\n\nLook at the keyboard. See the groups of two and three black keys? **Middle C is the white key immediately to the left of the two-black-key group closest to the piano's name.**\n\n## Play C–D–E–F–G\n\nPlace thumb (finger 1) on C, then a finger per white key. Press gently, count *one-and-two-and*. We'll go slow: 60 bpm.",
    audioRefs: [
      { id: "demo", label: "Your target (60 bpm)" },
      { id: "cmaj5_slow", label: "C-D-E-F-G, finger-by-finger" },
    ],
    exercisePlanId: "piano_l1_01_scale5",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.75, minPerDimension: { pitch: 0.8, rhythm: 0.6 } },
    estimatedMinutes: 8,
  },
  piano_l1_02_rhythm: {
    id: "piano_l1_02_rhythm",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Steady beat — quarters & halves",
    objectives: [
      "Clap quarter notes at 80 bpm with <50ms drift",
      "Hold a half note for exactly 2 beats",
      "Mix quarters and halves on one note (C)",
    ],
    writtenContent:
      "## The beat is a promise\n\nEvery quarter note is one click of the metronome. Every half note is two. We're not playing *faster*, we're playing *in time*.\n\nTap your foot with the metronome. Now play C on every tap. Now hold C for two taps. That's it — that's rhythm.",
    audioRefs: [{ id: "demo", label: "Target: 8 bars at 80 bpm" }],
    exercisePlanId: "piano_l1_02_quarter_halves",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 6,
  },
  piano_l1_03_twinkle: {
    id: "piano_l1_03_twinkle",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "First tune — Twinkle, Twinkle (right hand)",
    objectives: [
      "Play the melody of Twinkle using fingers 1–5 in C-position",
      "Keep steady tempo through bar 4",
      "Release cleanly between notes",
    ],
    writtenContent:
      "## You already know this tune\n\n*Twinkle, twinkle, little star* = C C G G A A G. *How I wonder what you are* = F F E E D D C. Your fingers don't move — only which finger presses changes.",
    audioRefs: [{ id: "demo", label: "Twinkle — whole tune, slow" }],
    exercisePlanId: "piano_l1_03_twinkle_rh",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 10,
  },
  piano_l1_04_left_hand: {
    id: "piano_l1_04_left_hand",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Adding the left hand — Twinkle bass",
    objectives: [
      "Find Middle C, then drop an octave to C3 for the left-hand thumb",
      "Play the bass line of Twinkle — same rhythm, lower octave",
      "Keep both hands relaxed; the left isn't louder than the right",
    ],
    writtenContent:
      "## One octave down\n\nYour left-hand thumb sits on **C3** — that's Middle C minus 12 keys (one octave down). Same finger numbers as the right hand but **mirrored**: finger 1 is still the thumb; finger 5 is the pinky, which now lives on the LEFT side.\n\n## The bass line\n\nIdentical rhythm to the right hand melody. Keep it quiet — the left hand is the foundation, not the roof.\n\n`C3 C3 G3 G3 A3 A3 G3 · F3 F3 E3 E3 D3 D3 C3`",
    audioRefs: [{ id: "demo", label: "Left-hand Twinkle, slow" }],
    exercisePlanId: "piano_l1_04_twinkle_lh",
    prerequisites: ["piano_l1_03_twinkle"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 8,
  },
  piano_l1_05_two_hands: {
    id: "piano_l1_05_two_hands",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Two hands together — full Twinkle",
    objectives: [
      "Play melody (RH) and bass (LH) simultaneously",
      "Keep steady tempo even when one hand is more interesting than the other",
      "Release both hands cleanly between phrases",
    ],
    writtenContent:
      "## The hardest thing in music\n\nThe first time you play two hands together, your brain will fight you. **That's normal.** Go stupid-slow — 40 bpm, one beat per breath if you need.\n\n## The secret\n\nDon't think about both hands at the same time. Think about the rhythm they share. When both hands land on beat 1, you only have to think about landing on beat 1.",
    audioRefs: [{ id: "demo", label: "Twinkle, both hands, 60 bpm" }],
    exercisePlanId: "piano_l1_05_twinkle_both",
    prerequisites: ["piano_l1_04_left_hand"],
    passCriteria: { minGradeOverall: 0.70 },
    estimatedMinutes: 12,
  },
  piano_l1_06_thumb_under: {
    id: "piano_l1_06_thumb_under",
    instrumentId: "piano",
    level: 1, tier: "standard",
    title: "Thumb under — the full C-major scale",
    objectives: [
      "Play C major one octave with fingering 1-2-3-1-2-3-4-5 ascending",
      "Thumb under for the 3→1 transition (on F going up, and F going down)",
      "Stay even — no gap when the thumb crosses",
    ],
    writtenContent:
      "## Why thumb-under exists\n\nYou have 5 fingers. The C-major scale has 8 notes. If you tried to use one finger per note, you'd run out after G. **Thumb-under** lets the same hand keep going smoothly up and down the keyboard forever.\n\n## The motion\n\nAscending: play E (finger 3), then sneak your thumb UNDER your hand to land on F (finger 1). Continue 2-3-4-5 up to C.\n\nDescending: play F (finger 1), then sneak finger 3 OVER your thumb to land on E. Continue down.\n\n## Even is everything\n\nIf you can hear the thumb-under, you're doing it too early or too late. The goal is invisible transitions.",
    audioRefs: [{ id: "demo", label: "C major scale, one octave, 80 bpm" }],
    exercisePlanId: "piano_l1_06_cmaj_scale",
    prerequisites: ["piano_l1_01_hand_shape"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { pitch: 0.8, rhythm: 0.7 } },
    estimatedMinutes: 10,
  },
  piano_l2_01_staff: {
    id: "piano_l2_01_staff",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Reading the treble staff",
    objectives: ["Name every line and space in treble clef", "Play a 4-bar sight-read", "Stay in time at 70 bpm"],
    writtenContent:
      "## The treble staff is 5 lines, 4 spaces\n\nLines from bottom up: **E G B D F** — mnemonic: *Every Good Boy Does Fine*.\nSpaces bottom up: **F A C E** — spells the word *FACE*.\n\nThat's the ENTIRE treble staff. Your right hand will read from this staff for the rest of your life.\n\n## Middle C sits just below\n\nThe bottom line of the treble staff is **E** (above Middle C). Middle C lives on a little 'ledger line' just underneath the staff.",
    audioRefs: [{ id: "demo", label: "Sight-read target · 4 bars, 70 bpm" }],
    exercisePlanId: "piano_l2_01_sightread",
    prerequisites: ["piano_l1_06_thumb_under"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 12,
  },
  piano_l2_02_bass_staff: {
    id: "piano_l2_02_bass_staff",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Reading the bass staff",
    objectives: [
      "Name every line and space in bass clef",
      "Play a 4-bar bass-line sight-read",
      "Switch between reading treble and bass within one piece",
    ],
    writtenContent:
      "## The bass staff is also 5 lines, 4 spaces\n\nLines bottom up: **G B D F A** — *Good Boys Do Fine Always*.\nSpaces bottom up: **A C E G** — *All Cows Eat Grass*.\n\nYour left hand will read from this staff.\n\n## Middle C sits just above\n\nThe top line of bass clef is A (below Middle C). Middle C lives on a ledger line right above the staff. So both staves share Middle C — they meet in the middle of the piano.",
    audioRefs: [{ id: "demo", label: "Bass-line sight-read, 70 bpm" }],
    exercisePlanId: "piano_l2_02_bass_sightread",
    prerequisites: ["piano_l2_01_staff"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  piano_l2_03_rests_ties: {
    id: "piano_l2_03_rests_ties",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Rests & ties — the silent parts matter",
    objectives: [
      "Recognize whole, half, and quarter rests on the staff",
      "Play a tied note as one sustained sound, not two separate ones",
      "Count accurately through silences",
    ],
    writtenContent:
      "## A rest is a note you can hear\n\nSilence in music isn't the absence of music — it's **part** of it. Rests come in the same values as notes:\n- Whole rest = 4 beats of silence (hangs below a line)\n- Half rest = 2 beats (sits on a line)\n- Quarter rest = 1 beat (the squiggly one)\n\nCount through rests just like through notes: *'one, two, THREE, four'* — the third beat is silent but still counted.\n\n## Ties are one note, not two\n\nA curved line connecting two same-pitch notes = hold the first through the second. Don't re-strike.",
    audioRefs: [{ id: "demo", label: "Rest + tie phrase" }],
    exercisePlanId: "piano_l2_03_rest_phrase",
    prerequisites: ["piano_l2_02_bass_staff"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 10,
  },
  piano_l2_04_accidentals: {
    id: "piano_l2_04_accidentals",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Sharps, flats, naturals — the black keys",
    objectives: [
      "Read a sharp (♯) as 'raise that note one key'",
      "Read a flat (♭) as 'lower that note one key'",
      "Understand a natural (♮) cancels a sharp or flat for the rest of the bar",
    ],
    writtenContent:
      "## The black keys have two names\n\nThe black key between C and D is both **C♯** (C-sharp) and **D♭** (D-flat). Same key, different name depending on the musical context.\n\n## An accidental lasts one bar\n\nWhen a sharp or flat appears before a note in a piece, it applies to **every repeat of that note in the same bar** — and resets at the barline. A natural sign (♮) cancels a sharp/flat mid-bar.\n\n## Sharps and flats are shortcuts\n\nRather than adding a sharp in front of every F in a piece, composers put a single ♯ at the start of each line (the 'key signature' — next lesson).",
    audioRefs: [{ id: "demo", label: "Phrase with sharps, flats, and naturals" }],
    exercisePlanId: "piano_l2_04_accidentals",
    prerequisites: ["piano_l2_03_rests_ties"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  piano_l2_05_key_sigs: {
    id: "piano_l2_05_key_sigs",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Key signatures — C, G, F",
    objectives: [
      "Recognize no sharps/flats = C major (or A minor)",
      "Recognize one sharp (F♯) = G major; one flat (B♭) = F major",
      "Apply the key signature to every note of that letter in the piece",
    ],
    writtenContent:
      "## The shortcut at the start\n\nAt the beginning of each staff line, composers write the **key signature** — a block of sharps or flats that apply to EVERY instance of those letter-name notes throughout the piece.\n\n- **No sharps/flats** = C major (all white keys)\n- **1 sharp (F♯)** = G major\n- **1 flat (B♭)** = F major\n\n## Why it matters\n\nInstead of littering the page with accidentals, the key signature declares 'play every F as F♯' once at the top. Your ear starts to expect the tonic (G, F, etc.) as home.",
    audioRefs: [{ id: "demo", label: "G major scale vs F major scale" }],
    exercisePlanId: "piano_l2_05_keysig_phrase",
    prerequisites: ["piano_l2_04_accidentals"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 12,
  },
  piano_l2_06_dynamics: {
    id: "piano_l2_06_dynamics",
    instrumentId: "piano",
    level: 2, tier: "standard",
    title: "Dynamics — loud, soft, and the shape between",
    objectives: [
      "Read p (piano) as soft, mf (mezzo-forte) as medium, f (forte) as loud",
      "Execute a crescendo (gradually louder) and decrescendo (gradually softer)",
      "Keep the rhythm steady even while the volume changes",
    ],
    writtenContent:
      "## Dynamics is the drama\n\nWithout volume contrast, music is robotic. Four core markings:\n- **pp** (pianissimo) = very soft\n- **p** (piano) = soft\n- **mf** (mezzo-forte) = medium-loud\n- **f** (forte) = loud\n- **ff** (fortissimo) = very loud\n\n## The shape between\n\nA **hairpin** opens toward the loud side. `<` = crescendo (get louder). `>` = decrescendo (get softer). The italic word *cresc.* or *dim.* means the same thing over a phrase.\n\n## Touch, not tension\n\nPlay loud by letting the weight of your arm fall into the key. Play soft by lifting slightly. Never by tensing your shoulder.",
    audioRefs: [{ id: "demo", label: "p → crescendo → f → decrescendo → p" }],
    exercisePlanId: "piano_l2_06_crescendo",
    prerequisites: ["piano_l2_05_key_sigs"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { dynamics: 0.7 } },
    estimatedMinutes: 10,
  },

  piano_l3_01_ode_to_joy: {
    id: "piano_l3_01_ode_to_joy",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Ode to Joy — first 8 bars",
    objectives: [
      "Play the main melody of Beethoven's Ode to Joy cleanly",
      "Hold the tempo steady at 90 bpm",
      "Phrase the two-bar groups naturally — breathe between them",
    ],
    writtenContent:
      "## Seven notes, one of humanity's most famous melodies\n\nBeethoven's 9th Symphony ends with a choir singing this tune. It uses only seven notes from the C major scale (E, D, F, G mostly) yet has carried meaning for two centuries.\n\n## The melody\n\n`E E F G · G F E D · C C D E · E D D`\n\nNotice the shape: steps up, a short descent, a long arc down, then the gentle fall. **Play it, then sing it in your head** — that's how you know if you're phrasing it right.",
    audioRefs: [{ id: "demo", label: "Ode to Joy, 8 bars, 90 bpm" }],
    exercisePlanId: "piano_l3_01_ode_melody",
    prerequisites: ["piano_l2_06_dynamics"],
    passCriteria: { minGradeOverall: 0.75 },
    estimatedMinutes: 12,
  },
  piano_l3_02_amazing_grace: {
    id: "piano_l3_02_amazing_grace",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Amazing Grace — arranged in C major",
    objectives: [
      "Play the Amazing Grace melody in 3/4 (waltz feel)",
      "Observe the pickup note (anacrusis) correctly",
      "Let the long notes breathe — don't rush to the next phrase",
    ],
    writtenContent:
      "## The pickup is not beat 1\n\nAmazing Grace starts on beat 3 — a pickup into the first bar proper. Count 'one two **three**' and start on *three*. If you start on one, everything's off by two beats for the whole song.\n\n## 3/4 is a waltz\n\nThree beats per bar: **ONE** two three, **ONE** two three. The downbeats feel heavier — that's the pulse.\n\n## The long notes\n\nDotted halves last three beats. Hold them. They're the emotional center of every phrase.",
    audioRefs: [{ id: "demo", label: "Amazing Grace, one verse" }],
    exercisePlanId: "piano_l3_02_amazing_grace",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 12,
  },
  piano_l3_03_keertanam: {
    id: "piano_l3_03_keertanam",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "A Carnatic keertanam on piano — raga Mohanam on the white keys",
    objectives: [
      "Play a 4-bar keertanam phrase using Sa Ri2 Ga3 Pa Dha2 (C D E G A)",
      "Observe the gamaka-like ornament on Ga (slight slide from D to E)",
      "Feel the 8-beat adi tala cycle — 4 + 2 + 2",
    ],
    writtenContent:
      "## Indian classical on Western keys\n\nRaga Mohanam (the South Indian name for what's close to a major pentatonic) uses only 5 notes: **Sa Ri Ga Pa Dha** = **C D E G A** on piano. Five white keys, five different moods.\n\n## Our phrase\n\n`C D E G A G E D C · G E G D C` — a simple characteristic phrase of the raga.\n\n## The ornament\n\nIn Carnatic music, Ga (E) isn't just played — it's approached with a slight slide from the note below. On piano we can approximate this with a fast grace-note from D into E.",
    audioRefs: [{ id: "demo", label: "Mohanam phrase with gamaka approximation" }],
    exercisePlanId: "piano_l3_03_mohanam",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 15,
  },
  piano_l3_04_autumn_leaves: {
    id: "piano_l3_04_autumn_leaves",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Autumn Leaves — jazz standard head, simplified",
    objectives: [
      "Play the opening A-section melody of 'Autumn Leaves' in E minor",
      "Observe the descending shape — each phrase drops a step lower",
      "Feel the minor-key mood: melancholy but never sad-for-its-own-sake",
    ],
    writtenContent:
      "## Jazz starts here\n\n'Les Feuilles Mortes' (Autumn Leaves) is the most played jazz standard in the world. We learn the melody first — the harmony, chord-melody voicings, and improvisation come in L5.\n\n## The shape\n\n`A B C E · D F# G# B · C B A C · B A` — four phrases, each starting lower than the last. The descent is the song's emotional arc.\n\n## Minor feels different\n\nMinor doesn't mean sad. It means weighted, contemplative. Play it slowly, with space between phrases.",
    audioRefs: [{ id: "demo", label: "Autumn Leaves A-section, slow" }],
    exercisePlanId: "piano_l3_04_autumn_leaves",
    prerequisites: ["piano_l3_01_ode_to_joy"],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 15,
  },
  piano_l3_05_hanon: {
    id: "piano_l3_05_hanon",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Hanon #1 — finger independence",
    objectives: [
      "Play Hanon exercise #1 right hand: C D F E F D E C + pattern shift up",
      "Keep all fingers equal in volume and timing",
      "Build to 90 bpm cleanly over a week",
    ],
    writtenContent:
      "## Hanon is boring. Do it anyway.\n\nCharles-Louis Hanon wrote 60 exercises in 1873 that every pianist still practices today. They're not music. They're gym for your fingers.\n\n## Exercise #1\n\nThe pattern: **C D F E F D E C** — then shift all notes up one step (D E G F G E F D) and repeat. Continue up through the C major scale.\n\n## Focus\n\n**Evenness** is the goal. Every finger strikes with equal volume and equal timing. If one finger is weaker, slow the metronome until it isn't.",
    audioRefs: [{ id: "demo", label: "Hanon #1, first pattern, 60 bpm" }],
    exercisePlanId: "piano_l3_05_hanon_1",
    prerequisites: ["piano_l2_06_dynamics"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { rhythm: 0.78, consistency: 0.75 } },
    estimatedMinutes: 10,
  },
  piano_l3_06_accompaniment: {
    id: "piano_l3_06_accompaniment",
    instrumentId: "piano",
    level: 3, tier: "standard",
    title: "Chord accompaniment — I-IV-V-I in C major",
    objectives: [
      "Play C, F, G, C as block chords in the left hand",
      "Hold each chord for 2 beats before changing",
      "Sing or hum a simple melody over the top",
    ],
    writtenContent:
      "## The progression that's everything\n\nI-IV-V-I is the chord progression under half of Western music: pop, rock, folk, blues, classical. In C major: **C → F → G → C**.\n\n## Building the chords\n\n- C = C + E + G (root + third + fifth)\n- F = F + A + C\n- G = G + B + D\n- Back to C\n\nLeft hand plays the chord; right hand can play or sing the melody.\n\n## Why it works\n\nThe V (G) 'wants' to resolve to the I (C) — that pull is the engine of nearly every phrase ending you've ever heard.",
    audioRefs: [{ id: "demo", label: "C F G C, 2 beats each, 80 bpm" }],
    exercisePlanId: "piano_l3_06_chord_progression",
    prerequisites: ["piano_l2_05_key_sigs"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 15,
  },

  guitar_l1_01_hold: {
    id: "guitar_l1_01_hold",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Holding the guitar & your first string",
    objectives: [
      "Sit or stand with the guitar's body flat against you, neck angled up slightly",
      "Identify the 6 strings by letter (low to high: E A D G B E)",
      "Pluck each open string cleanly and hear its pitch",
    ],
    writtenContent:
      "## The guitar is an armful\n\nBody flat against your ribs. Neck tilted up at about 10–15° — not pointing at the floor, not pointing at the ceiling. If your wrist hurts after 5 minutes, your posture is wrong; adjust before you continue.\n\n## Six strings, two Es\n\nFrom the thickest string (closest to your face) to the thinnest: **E - A - D - G - B - E**. The two Es are two octaves apart — low E2 and high E4. The rest run: A2, D3, G3, B3.\n\n## Just pluck\n\nWith your thumb or a pick, sound each open string one by one. Listen. A clean open string rings — if it buzzes, your finger is accidentally touching a fret.",
    audioRefs: [{ id: "demo", label: "Six open strings, low to high" }],
    exercisePlanId: "guitar_l1_01_open_strings",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.65 },
    estimatedMinutes: 8,
  },
  guitar_l1_02_first_fret: {
    id: "guitar_l1_02_first_fret",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "Your first fretted notes — the low E string",
    objectives: [
      "Press down just behind each fret (not on it, not in the middle)",
      "Play E (open) → F (1st fret) → G (3rd fret) → A (5th fret)",
      "Keep each note clean and ringing",
    ],
    writtenContent:
      "## Where to press\n\nThe fret itself is the metal bar. Press the string **just behind** the fret (on the headstock side) — not on the metal, not way back. Close to the fret = clean note with minimal pressure.\n\n## Four notes on one string\n\nLow E string: open = E · 1st fret = F · 3rd fret = G · 5th fret = A. That's the bottom half of an A-minor scale without moving to another string.",
    audioRefs: [{ id: "demo", label: "E · F · G · A on low E string" }],
    exercisePlanId: "guitar_l1_02_e_string_walk",
    prerequisites: ["guitar_l1_01_hold"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.75 } },
    estimatedMinutes: 10,
  },
  guitar_l1_03_first_chord: {
    id: "guitar_l1_03_first_chord",
    instrumentId: "guitar",
    level: 1, tier: "standard",
    title: "First chord — Em",
    objectives: [
      "Fret E minor: 2nd fret of the A and D strings, fingers 2 and 3",
      "Strum all six strings cleanly",
      "Release and re-fret 5 times in a row without buzzing",
    ],
    writtenContent:
      "## E minor, the welcoming chord\n\nEm uses just two fretted notes: **finger 2 on the 2nd fret of A**, **finger 3 on the 2nd fret of D**. Every other string rings open.\n\n## The strum\n\nRelax your pick hand. Let the pick fall through all 6 strings — don't stab, don't scrape. A full Em should sound lush; if it buzzes, check your finger tips aren't touching neighboring strings.",
    audioRefs: [{ id: "demo", label: "Em chord — strum x4" }],
    exercisePlanId: "guitar_l1_03_em_strum",
    prerequisites: ["guitar_l1_02_first_fret"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },

  violin_l1_01_hold: {
    id: "violin_l1_01_hold",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "Holding the violin & bowing an open string",
    objectives: [
      "Rest the violin on your collarbone; chin gently on the rest — not clamped",
      "Hold the bow with a relaxed grip: thumb curved, pinky on top, hair angled toward the bridge",
      "Draw a straight bow on the open A string for a clean, singing tone (4 seconds)",
    ],
    writtenContent:
      "## Where the violin lives\n\nThe violin's **body** rests on your collarbone. Your chin sits on the chinrest — **gently**. If your shoulder is raised or your neck is straining, you're holding it wrong; take it off, shake out, try again.\n\n## The bow is a breath\n\nBow grip: thumb curved like a hook, pinky balanced on top of the stick, other fingers draped. The bow moves parallel to the bridge — not swinging in an arc. A straight bow = a straight tone.\n\n## Your first note\n\nBow the open **A string** — that's the second-highest string. No fingers touching the fingerboard yet. Down-bow from frog to tip, slowly, 4 seconds. Then up-bow back. Clean tone, no scratching.",
    audioRefs: [{ id: "demo", label: "Open A, 4-second down-bow + up-bow" }],
    exercisePlanId: "violin_l1_01_open_a",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.65, minPerDimension: { tone: 0.65 } },
    estimatedMinutes: 10,
  },
  violin_l1_02_first_finger: {
    id: "violin_l1_02_first_finger",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "First finger — playing B on the A string",
    objectives: [
      "Curl your first finger onto the A string about one inch from the nut",
      "Press firmly enough to stop the string cleanly; don't squeeze",
      "Bow the result: it should sound a whole step up from A — that's B",
    ],
    writtenContent:
      "## Intonation is everything\n\nThe violin has **no frets**. There's no 'right' spot — there's only 'in tune' and 'not in tune'. Your ear is the only judge. Start by listening to a reference B, then try to match it.\n\n## Where the finger goes\n\nLook at the fingerboard. About **one inch from the nut** (the bone at the top where the strings begin), press your first finger down firmly. Keep it curved, not flat. Bow slowly — if you hear a clean note, you found B. If it's buzzing, press harder or move slightly.",
    audioRefs: [{ id: "demo", label: "B on A string — reference tone" }],
    exercisePlanId: "violin_l1_02_a_to_b",
    prerequisites: ["violin_l1_01_hold"],
    passCriteria: { minGradeOverall: 0.68, minPerDimension: { pitch: 0.7 } },
    estimatedMinutes: 10,
  },
  violin_l1_03_first_phrase: {
    id: "violin_l1_03_first_phrase",
    instrumentId: "violin",
    level: 1, tier: "standard",
    title: "First phrase — A B C♯ D (D-major tetrachord)",
    objectives: [
      "Add finger 2 (C♯) and finger 3 (D) on the A string",
      "Play the four notes as a rising phrase, clean intonation",
      "Keep the bow steady — one note per bow stroke",
    ],
    writtenContent:
      "## Four notes, one bow each\n\nA (open) → B (finger 1) → C♯ (finger 2) → D (finger 3). That's a **tetrachord** — the lower half of a D major scale.\n\nFinger 2 sits **close to** finger 1 (only a half-step gap feels tight, but this is a whole step — about an inch). Finger 3 is a half-step from finger 2 — fingers almost touching.\n\n## Listen as you play\n\nIf the note sounds 'off', it IS off. Move the finger a millimeter. This is the whole game of violin — listen, adjust, repeat.",
    audioRefs: [{ id: "demo", label: "A B C# D rising, 60 bpm" }],
    exercisePlanId: "violin_l1_03_d_tetrachord",
    prerequisites: ["violin_l1_02_first_finger"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.72 } },
    estimatedMinutes: 12,
  },

  drums_l1_01_grip: {
    id: "drums_l1_01_grip",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Grip, posture, and your first strokes",
    objectives: [
      "Hold sticks with a matched grip — thumb and index form the fulcrum, other fingers loose",
      "Sit with your kick-drum foot flat, hi-hat foot on its pedal, snare between your knees",
      "Strike the snare four times at 80 bpm — equal volume, equal spacing",
    ],
    writtenContent:
      "## The stick is a pendulum\n\nHold lightly. The stick should bounce off the drum, not be forced into it. If your forearms are tense, you're gripping too hard.\n\n## Matched grip\n\nBoth hands the same: thumb pad on one side of the stick, index finger on the other, forming a pinch (the 'fulcrum'). Other three fingers drape underneath — they guide, they don't grip.\n\n## First strokes\n\n4 snare hits at 80 bpm. Goal: each hit sounds identical. If they don't, you're gripping inconsistently.",
    audioRefs: [{ id: "demo", label: "4 snare hits, 80 bpm" }],
    exercisePlanId: "drums_l1_01_snare_4",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 8,
  },
  drums_l1_02_kick_snare: {
    id: "drums_l1_02_kick_snare",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "The backbeat — kick on 1&3, snare on 2&4",
    objectives: [
      "Play kick on beats 1 and 3, snare on beats 2 and 4",
      "Keep both feet and hands relaxed — no stomping the kick",
      "Loop it for 8 bars without breaking tempo",
    ],
    writtenContent:
      "## The most important pattern in popular music\n\nKick-1, snare-2, kick-3, snare-4. Repeat forever. Half the world's music sits on this foundation.\n\n## The kick is quiet\n\nDon't stomp. A controlled heel-up motion gives you power and evenness. The drum does the work; your leg is a lever.\n\n## Count out loud\n\nSeriously — say **'ONE two THREE four'** while you play. Your mouth locks in the timing that your limbs are still learning.",
    audioRefs: [{ id: "demo", label: "Backbeat loop, 8 bars @ 80 bpm" }],
    exercisePlanId: "drums_l1_02_backbeat",
    prerequisites: ["drums_l1_01_grip"],
    passCriteria: { minGradeOverall: 0.7 },
    estimatedMinutes: 10,
  },
  drums_l1_03_hihat: {
    id: "drums_l1_03_hihat",
    instrumentId: "drums",
    level: 1, tier: "standard",
    title: "Add the hi-hat — your first full groove",
    objectives: [
      "Add closed hi-hat on every quarter note (1 2 3 4)",
      "Keep kick and snare from L1.2 pattern intact underneath",
      "Play 8 bars — three limbs, one tempo",
    ],
    writtenContent:
      "## Three limbs, one rhythm\n\nRight hand plays hi-hat on every beat: 1, 2, 3, 4. Left hand plays snare on 2 and 4. Right foot plays kick on 1 and 3. Left foot stays on the hi-hat pedal, keeping it closed.\n\nIf your brain protests, that's normal. Go slower — 60 bpm, even 50. **Coordination is a physical skill, not a musical one**. It will come.",
    audioRefs: [{ id: "demo", label: "Full rock groove, 8 bars @ 80 bpm" }],
    exercisePlanId: "drums_l1_03_full_groove",
    prerequisites: ["drums_l1_02_kick_snare"],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { rhythm: 0.75 } },
    estimatedMinutes: 12,
  },

  sitar_l1_01_sa: {
    id: "sitar_l1_01_sa",
    instrumentId: "sitar",
    level: 1, tier: "standard",
    title: "Finding Sa & tuning the drone",
    objectives: [
      "Identify Sa (tonic) and Pa (fifth) on the main string",
      "Set the tanpura / drone to match",
      "Sustain a clean Sa for 10 seconds with the mizrab",
    ],
    writtenContent:
      "## Sa is home\n\nBefore any raga, there is Sa. It's the tonic, the anchor, the first breath of every phrase. The drone — tanpura or keyboard drone — gives you Sa and Pa forever. Listen first, play second.\n\n## Your mizrab\n\nWire plectrum, right index finger. Down-stroke = **Da**. Up-stroke = **Ra**. For Sa, just Da. Clean. Ringing. Ten seconds.",
    audioRefs: [{ id: "drone", label: "Tanpura drone in C" }, { id: "sa_demo", label: "Guruji plays Sa" }],
    exercisePlanId: "sitar_l1_01_sustain_sa",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.7, minPerDimension: { pitch: 0.8, tone: 0.65 } },
    estimatedMinutes: 10,
  },
  sitar_l4_01_yaman_alap: {
    id: "sitar_l4_01_yaman_alap",
    instrumentId: "sitar",
    level: 4, tier: "pro",
    title: "Raga Yaman — opening alap with meend",
    objectives: [
      "Sustain Sa then climb to Ga cleanly",
      "Execute meend from Ma down to Ga",
      "Breathe at the end of each phrase",
    ],
    writtenContent:
      "## The evening raga\n\nYaman is the gentlest welcome to Hindustani classical. Thaat: Kalyan. Vadi: Ga. Samvadi: Ni. Time: early evening.\n\n**Aaroha:** Ni Re Ga Ma Dha Ni Sa'  \n**Avaroha:** Sa' Ni Dha Pa Ma Ga Re Sa  \n**Pakad:** Ni Re Ga, Ma Dha Ni Sa'\n\nStart on Sa. Breathe. Climb slowly to Ga. From Ma, bend (meend) down to Ga in one continuous motion — that's the heart of Yaman.",
    audioRefs: [{ id: "demo", label: "Ustad's alap in Yaman" }],
    exercisePlanId: "sitar_l4_01_yaman_meend",
    prerequisites: ["sitar_l1_01_sa"],
    passCriteria: { minGradeOverall: 0.72, minPerDimension: { pitch: 0.75, tone: 0.7 } },
    estimatedMinutes: 15,
  },

  tabla_l1_01_dha: {
    id: "tabla_l1_01_dha",
    instrumentId: "tabla",
    level: 1, tier: "standard",
    title: "Your first bol — Dha",
    objectives: [
      "Strike Dha cleanly — right finger on the syahi + left hand open",
      "Produce a ringing, pitched sound",
      "Repeat 16 times on the beat at 80 bpm",
    ],
    writtenContent:
      "## Dha = Dha + Ge\n\n**Dha** is the sound of both hands together: Dha (right, ringing open stroke on the dayan) + Ge (left, open palm slap on the bayan). It's the first bol of teentaal.\n\nGet one clean Dha. Then 16 in a row.",
    audioRefs: [{ id: "demo", label: "Guruji plays 16x Dha" }],
    exercisePlanId: "tabla_l1_01_dha_16",
    prerequisites: [],
    passCriteria: { minGradeOverall: 0.72 },
    estimatedMinutes: 8,
  },
};

export const listLessonsForInstrument = (instrumentId: string) =>
  Object.values(LESSONS)
    .filter((l) => l.instrumentId === instrumentId)
    .sort((a, b) => a.level - b.level);

export const getLesson = (id: string) => LESSONS[id];
