export type Tier = "standard" | "pro" | "genius";
export type Level = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;
export type Origin = "western" | "indian_classical" | "global";
export type Family =
  | "keyboard" | "fretted" | "bowed" | "woodwind" | "brass"
  | "perc_pitched" | "perc_unpitched" | "voice" | "electronic";

export interface Instrument {
  id: string;
  name: string;
  family: Family;
  origin: Origin;
  accent: string;             // tailwind color class suffix, e.g. "keyboard"
  glyph: string;              // emoji or unicode for placeholder hero
  blurb: string;
  heroImage?: string;
  tuningRef: { hz: number; noteMap: "12-TET" | "sa-based-C" };
  controls: Array<{
    id: string; name: string; label: string;
    description: string; audioSample?: string;
  }>;
  sampleAudio: Array<{ id: string; label: string; url?: string; noteName?: string }>;
  pedagogyTrackId: string;
  difficultyFloor: 1 | 2 | 3;
  micSetupHints: string[];
}

// ---------- Multi-drill practice phases ----------
//
// Every phase of the 9-phase lesson runner can expose multiple drills so
// learners spend more time going deep at each level before advancing.
// All fields are optional — when unset, the phase falls back to the
// single-exercise rendering using `exercisePlanId`.

export interface TeachPoint {
  id: string;
  heading: string;           // short title for this teaching point
  body: string;              // markdown explanation
  audioRefId?: string;       // optional audio illustration
}

export interface DemoClip {
  id: string;
  label: string;             // e.g. "Full passage · 100%", "Left hand only", "Section A slow"
  description?: string;
  notes?: TargetNote[];
  onsets?: number[];
  tempoBpm?: number;         // playback tempo for this clip
}

export interface DissectPoint {
  id: string;
  label: string;             // e.g. "The tricky F#", "Bar 3 meend"
  description: string;
  notes?: TargetNote[];      // optional mini-pattern to loop
  controlRefId?: string;     // optional instrument control (mirrors DissectionOverlay)
}

export interface VirtualTryPrompt {
  id: string;
  prompt: string;            // e.g. "Find F#4 on the fretboard"
  /** Notes the learner must hit on the on-screen instrument. */
  targetNotes: string[];
  /** How many of `targetNotes` must be pressed to clear this drill. */
  minHits?: number;
}

export interface GuidedPassVariation {
  id: string;
  label: string;             // e.g. "Full phrase", "First half", "Contour only"
  description?: string;
  notes?: TargetNote[];
  onsets?: number[];
}

export interface AttemptVariation {
  id: string;
  label: string;             // e.g. "Slow take", "Full tempo", "Improvise over it"
  description?: string;
  /** Optional override exerciseId; defaults to the parent lesson's exercise. */
  exerciseId?: string;
  tempoFactor?: number;      // relative to the base exercise tempo (1.0 = same)
}

export interface LessonDrills {
  teach?: TeachPoint[];
  demo?: DemoClip[];
  dissect?: DissectPoint[];
  virtualTry?: VirtualTryPrompt[];
  guided?: GuidedPassVariation[];
  attempt?: AttemptVariation[];
}

export interface Lesson {
  id: string;
  instrumentId: string;
  level: Level;
  tier: Tier;
  title: string;
  objectives: string[];
  writtenContent: string;     // markdown
  audioRefs: Array<{ id: string; label: string; url?: string; transcript?: string }>;
  exercisePlanId: string;
  prerequisites: string[];
  passCriteria: { minGradeOverall: number; minPerDimension?: Partial<DimScores> };
  estimatedMinutes: number;
  /**
   * Optional multi-drill content. Each phase in the 9-phase runner can
   * step through these so a learner spends 5-10 minutes deep in each
   * phase instead of a single pass. Generated by lessonDrillGenerator
   * for every lesson that doesn't hand-author its own.
   */
  drills?: LessonDrills;
}

export type ExerciseType =
  | "play_note" | "play_scale" | "play_chord" | "rhythm_clap"
  | "sight_read" | "play_along" | "improvise" | "compose" | "ear_train";

export interface TargetNote { pitch: string; startMs: number; durationMs: number; velocity?: number; finger?: number; }
export interface TargetChord { root: string; quality: string; startMs: number; durationMs: number; }
export interface RagaPhrase { ragaId: string; svaras: string[]; gamakaHints: string[]; }

export interface Exercise {
  id: string;
  type: ExerciseType;
  instrumentId: string;
  title: string;
  targetPattern: {
    notes?: TargetNote[];
    chords?: TargetChord[];
    onsets?: number[];
    ragaPhrase?: RagaPhrase;
  };
  tempo: { bpm: number; meter: [number, number] };
  gradingRubricId: string;
  referenceAudioUrl?: string;
}

export interface DimScores {
  pitch: number; rhythm: number; tone: number; dynamics: number; consistency: number;
}

export interface Rubric {
  id: string;
  weights: DimScores;
  passThreshold: number;
  pitchToleranceCents: number;
  rhythmToleranceMs: number;
  feedbackBank: Record<keyof DimScores, { minor: string[]; major: string[] }>;
}

export interface Raga {
  id: string; name: string; thaat: string; time: string;
  aaroha: string[]; avaroha: string[];
  vadi: string; samvadi: string; pakad: string[];
  moodTags: string[];
  equivalentScale: { root: string; mode: string };
}

export interface Taal {
  id: string; name: string; matras: number;
  vibhag: number[]; theka: string[]; clapPattern: ("X" | "0" | number)[];
}

export interface TierEntry {
  levelId: Level; tier: Tier; label: string; xpThreshold: number; color: string;
}

export interface Mentor {
  id: string; name: string; photoGlyph: string; role: "maestro" | "coach" | "guru";
  bio: string;
  instrumentExpertise: string[];
  styleExpertise: string[];
  defaultLines: string[];
  registerPrompt: string;
}

export interface Artist {
  id: string; name: string; photoGlyph: string; era: string; origin: string;
  instruments: string[];
  signatureLicks: Array<{ id: string; label: string; exerciseId?: string }>;
  styleFingerprint: { tempoRange: [number, number]; scaleBias: string; ornamentTags: string[] };
  sampleTracks: Array<{ title: string; url?: string; licensedUse: "excerpt" | "link_only" }>;
  unlockTier: "pro" | "genius";
  blurb: string;
}

export interface Quest {
  id: string; title: string; blurb: string;
  scope: "daily" | "streak" | "mastery" | "cross_instrument";
  instrumentId?: string;
  goal: {
    type: "play_minutes" | "pass_exercise" | "complete_lesson" | "perfect_run" | "record_recital" | "compose_bars";
    target?: string; count: number;
  };
  reward: { xp: number; coins?: number; hearts?: number; badgeId?: string };
  giverMentorId?: string;
  progress?: number;
}

export interface SongLibraryEntry {
  id: string; title: string; artistId?: string; genre: string;
  difficultyByInstrument: Record<string, Level>;
  copyrightNote: "public_domain" | "licensed" | "user_performance";
  blurb: string;
}

// ---------- Exams ----------

export type ExamScope = "lesson" | "level" | "grade";

export type ExamQuestion =
  | {
      id: string;
      type: "mcq";
      prompt: string;
      options: string[];              // 2-4 options
      correctIndex: number;
      explanation: string;
    }
  | {
      id: string;
      type: "listening";
      prompt: string;                 // "Which scale is this?"
      audioRef: { notes: Array<{ pitch: string; startMs: number; durationMs: number }> };  // Tone.js-playable
      options: string[];
      correctIndex: number;
      explanation: string;
    }
  | {
      id: string;
      type: "notation";
      prompt: string;                 // "Name this note"
      staff: { noteOnStaff: string };  // simple: e.g. "E4" rendered on treble staff
      options: string[];
      correctIndex: number;
      explanation: string;
    }
  | {
      id: string;
      type: "tap_rhythm";
      prompt: string;
      targetOnsets: number[];          // ms timestamps for the correct tap pattern
      tempoBpm: number;
      toleranceMs: number;
      explanation: string;
    }
  | {
      id: string;
      type: "free_text";
      prompt: string;
      rubric: string;                  // what the AI grader looks for
      expectedConcepts: string[];
      explanation: string;
    }
  | {
      id: string;
      type: "practical";
      prompt: string;
      exerciseId: string;              // link into exerciseCatalog
      minComposite: number;
      explanation: string;
    };

export interface Exam {
  id: string;
  scope: ExamScope;
  instrumentId: string;
  lessonId?: string;                 // for "lesson" scope
  level?: Level;                     // for "level" scope
  tier?: Tier;                       // for "grade" scope
  title: string;
  questions: ExamQuestion[];
  passThreshold: number;             // fraction of questions correct, e.g. 0.67
}
